### ISSUE TITLE
Add extra file to created package

### ISSUE THREAD

**Issue by victorgianvechio** [electron-userland/electron-packager#1011]
I have a folder in my project named "xpdf-tools" and wanted it to be added to the created package. How can I do this?

my package.json

```
"scripts": {
        "start": "electron .",
        "build": "electron-packager . --out=./build/  --overwrite --prune --asar --platform=win32 --arch=x64 --icon=./app/assets/img/icon/pdf.ico --ignore=./gitignore --executableName=\"Acerta Holerite\" --version-string.ProductName=\"acerta-holerite\""
    }
```

**Comment by malept** [comment]
Unfortunately, due to the limited amount of time of the maintainers and the limited amount of information present in this issue, we cannot help debug your app at this time. Instead, you should make sure your issue is not already answered in our [Frequently Asked Questions](https://github.com/electron-userland/electron-packager/blob/master/docs/faq.md) document, and consider using one of the [community forums](https://electronjs.org/community), as there are more people there available to answer questions.
