### ISSUE TITLE
Ignore `electron-prebuilt` and `electron-packager` by default

### ISSUE THREAD

**Issue by sindresorhus** [electron-userland/electron-packager#13]
So I don't have to `$ atom-shell-packager . App --ignore=node_modules/electron-prebuilt --ignore=node_modules/electron-packager`.

**Comment by remixz** [comment]
If you have those dependencies in your `devDependencies`, you can pass `--prune`, and it'll remove those from the bundle, along with any other `devDependencies`.

In any case though, :+1: to that, would be a good default.

**Comment by maxogden** [comment]
patch welcome :)

**Comment by sindresorhus** [comment]
Should also exclude the `.git` folder by default.

**Comment by stefanbuck** [comment]
Maybe should get the ignores from the `.gitignore`

**Comment by sindresorhus** [comment]
Or like npm, either use the whitelisting `files` array in package.json or the .npmignore blacklist.

**Comment by jden** [comment]
:+1: for copying the npm ignore algorithm:

whitelist `files` in package.json || blacklist .npmignore || blacklist .gitignore || *

**Comment by englercj** [comment]
:+1: For using the npm algorithm but I don't think that is enough to fix the need I have with choosing the right node_modules. I won't put "node_modules/..." in my package.json files array, because I wouldn't want them in my npm tgz, but there are like 2 modules that need to be included in the electron package.

I have a bunch of normal dependencies that are used at runtime, but are compiled into the renderer code (browserify). I only have like 1 or 2 modules of my "dependencies" that I want to include in the output package that are used by the app code. I need a way to *whitelist* modules instead of only allowing *blacklisting*.

**Comment by jenslind** [comment]
This would be great! Could the use of a custom field like `buildFiles` instead of `files` be an option? Just to not interfere with npm.

**Comment by maxogden** [comment]
this seems like a problem not specific to this module, so a generic solution would be preferred, e.g. the ability for the user to run a pre-package script that did whatever they want, and then someone can make a 'strip-non-essential-files' CLI module that can be used there

**Comment by jden** [comment]
@sindresorhus is there anything else in this issue that was not addressed by #24? Can it be closed?

**Comment by sindresorhus** [comment]
@maxogden Not optimal as the user probably don't want those files deleted, only ignored from the packaged app, and the script would have no knowledge of how `electron-packager` packages the apps. The ignore logic could of course be a separate module `electron-packager` depends on.

@jden When we have an agreement on the above.

**Comment by malept** [comment]
electron-packager currently ignores `node_modules/electron-packager`, `node_modules/electron-prebuilt`, and `.git` by default, which means the issue title is now a reality (and then some). Please file any further enhancements to the ignore logic in separate issues.

**Comment by NameNull** [comment]
if i want to ignore *.bat and *.sh ,how can i spell
