### ISSUE TITLE
swap out fs-extra.copy for tar-fs

### ISSUE THREAD

**Issue by maxogden** [electron-userland/electron-packager#151]
to fix https://github.com/maxogden/electron-packager/issues/150

we should switch to using https://www.npmjs.com/package/tar-fs: `tarfs.pack().pipe(tarfs.extract())`, its like `JSON.parse(JSON.stringify(obj))` but for filesystems :) it's a simpler solution than using ncp, which is not currently maintained

patch welcome!

**Comment by sindresorhus** [comment]
There's also [cpy](https://github.com/sindresorhus/cpy).

**Comment by maxogden** [comment]
I wrote this for something else just now, its 12 lines: https://github.com/maxogden/cptar

**Comment by natew** [comment]
Wondering if this would fix an issue I'm having...

When I run packager I get errors across a few apps. Chrome quits itself most fo the time and won't re-open without crashing until after packager runs. And then VSCode complains of too many open file references.

Guessing this is due to large amounts of node_modules. Currently am able to build most of the app into webpack bundles which may be the way to go.

Just realized this is a couple years old...

**Comment by malept** [comment]
@natew Probably not. `tar-fs` is the transfer mechanism, it doesn't change the way the JavaScript is stored on disk.

**Comment by malept** [comment]
I've been testing this enhancement off and on over the past week. The amount of code that has to change isn't bad, however there is a consistent performance decrease that I've noticed. It adds about a minute to the testsuite when I run it locally.

**Comment by malept** [comment]
For reference: any replacement of `fs-extra.copy` has to have, at minimum, support for optionally dereferencing symlinks and a user-configurable filter.

**Comment by malept** [comment]
I'm closing this due to the performance drop I saw.
