### ISSUE TITLE
Electron Framework.framework fails sealed check

### ISSUE THREAD

**Issue by aekeus** [electron-userland/electron-packager#227]
After signing our Electron based app and its associated directories, the Electron Framework.framework directory fails a spctl --assess check:

    spctl --assess Electron\ Framework.framework
    Electron Framework.framework/: a sealed resource is missing or invalid

The codesign signing succeeds:

    codesign --force --sign XXXXXX --verbose Electron\ Framework.framework
    Electron Framework.framework/: replacing existing signature
    Electron Framework.framework/: signed bundle with Mach-O thin (x86_64)     [com.github.electron.framework]

Moving the files from the Electron.app directory seems to cause the seal to become invalid. Ultimately this impacts the ability to auto update. Gatekeeper flags the package as invalid because of the failing sealed contents, and discards the update.

**Comment by rishson** [comment]
@aekeus what does `spctl` give for your electron app:
`spctl --verbose=4 --assess --type execute myApp`
Does this pass but a check of the Electron Framework fail?

**Comment by malept** [comment]
Since the original issue reporter has not responded to the request for additional information in over two months, I'm going to assume that they either found the answer in another manner or decided not to pursue this issue. If I'm incorrect, they can respond with answers to the questions posed, and I'll reopen.
