### ISSUE TITLE
A javascript Error occurred in the main process

### ISSUE THREAD

**Issue by NanaPhil** [electron-userland/electron-packager#303]
Uncaught Exception:
TypeError: Arguments to path.join must be strings
    at Object.posix.join (path.js:467:13)
    at Object.<anonymous> (/<path>/<path>/Appname/Contents/Resources/atom.asar/browser/lib/init.js:106:21)
    at Object.<anonymous> (/<path>/Appname.app/Contents/Resources/atom.asar/browser/lib/init.js:108:4)
    at Module._compile (module.js:428:26)
    at Object.Module._extensions..js (module.js:446:10)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
    at Function.Module.runMain (module.js:469:10)
    at startup (node.js:125:18)
    at node.js:960:3

**Comment by malept** [comment]
Thanks for filing an issue! In order to help you with your problem, we're going to need more information about it. In particular:

*  Which version of electron-packager are you using?



* What CLI arguments are you passing? Alternatively, if you are using the API, what parameters are you passing to the `packager()` function?



* What version of [Electron](http://electron.atom.io) are you building with? (The value of the `version` parameter, or the specific version of `electron-prebuilt` in `package.json`)




* What is the host platform are you running electron-packager on? Please supply name, version, and architecture.


* What target platform(s)/architecture(s) are you building for?



* Is there a stack trace in the error message you're seeing? If so, please paste it (preferably in a preformatted block).



* Please provide either a failing testcase or detailed steps to reproduce your problem.

**Comment by NanaPhil** [comment]
I have an existing app built from this starter.

 https://github.com/val-samonte/electron-angular-typescript

i added installed eletron-packager globally and run electron-packager .
--all.

it builds the various outputs into the folders. but when i run the output
.app file in osx . i get that error.


ᐧ

**Comment by malept** [comment]
Since that starter is several months old, it may not be compatible with a recent version of electron-packager. As I asked above, which version of Electron are you building with?

**Comment by NanaPhil** [comment]
V0.34.2
ᐧ

**Comment by malept** [comment]
In the exception, there's no reference to app code, and you're using an old version of Electron, so I don't think this is an electron-packager problem.
