### ISSUE TITLE
Won't set icon

### ISSUE THREAD

**Issue by matthewdias** [electron-userland/electron-packager#305]
In my project i have `assets/icon.icns`, and when running with `--icon=assets/icon`, the packaged .app, doesn't have my icon.

> Which version of electron-packager are you using?

`6.0.0`

> What CLI arguments are you passing? Alternatively, if you are using the API, what parameters are
> you passing to the `packager()` function?

`electron-packager . --all --icon=assets/icon --out=builds`

> What version of [Electron](http://electron.atom.io) are you building with?

`0.37.4`

> What is the host platform are you running electron-packager on?

OS X, 10.11.4, 64bit

> What target platform(s)/architecture(s) are you building for?

OS X, 64bit

**Comment by malept** [comment]
Thanks for filing an issue! This bug has already been fixed in master, via #301. We're waiting for another fix related to the Electron 0.37.4 release to upload a new version of electron-packager to NPM (see: https://github.com/electron-userland/electron-packager/milestones/6.0.1). Until that happens, install electron-packager using the Git URL.
