### ISSUE TITLE
default mac icon (icns) is atom.icns should be electron.icns

### ISSUE THREAD

**Issue by guatedude2** [electron-userland/electron-packager#310]
The default icon name is "atom.icns" in `mac.js` should be `electron.icns` as it shows that icon in the default plist .

To fix this issue:
Line 168 of `mac.js` is:
```
              ncp(icon, path.join(contentsPath, 'Resources', 'atom.icns'), cb)
```
should be:
```
              ncp(icon, path.join(contentsPath, 'Resources', 'electron.icns'), cb)
```
> Which version of electron-packager are you using?
6.0.0

`electron-packager app/ --app-bundle-id=com.example.app --platform=darwin --arch=x64 --prune --asar --icon=./icon.icns --out=build/`

> What version of [Electron](http://electron.atom.io) are you building with?

v0.37.5

> What is the host platform are you running electron-packager on?

OSX El Capitan

> What target platform(s)/architecture(s) are you building for?

osx - x64

**Comment by malept** [comment]
Thanks for filing an issue on this. It's been fixed in master (#300/#301), but we're waiting for another pull request (#298) to get merged, which is also affected by Electron >= 0.37.4.

Two workarounds exist, until 6.0.1 is released:

* Install electron-packager using the GitHub syntax (see `npm install --help`)
* Package your Electron app using a version of Electron earlier than 0.37.4, for example 0.37.3.
