### ISSUE TITLE
Missing parameters error

### ISSUE THREAD

**Issue by Osmosis311** [electron-userland/electron-packager#370]
No matter what combination of parameters I try, even using EPI, I'm getting the following error:

Error: Unable to infer name or version. Please specify a name and version.

Using latest version, installed tonight.

**Comment by malept** [comment]
Let's start with the basics, since you didn't provide an example (so there's not much to go off of):

Does your project have a `package.json`?

If so, is it in the same directory that you're running `electron-packager` in?

**Comment by mfraiss** [comment]
Hi @Osmosis311,

I had the same errors before. My package.json looks like this:

`{
  "productName"   : "HelloWorld",
  "name"    : "Hello World",
  "version" : "0.1.0",
  "main"    : "main.js"
}
`

And for me the following command line call worked:
`electron-packager ./helloworld --platform=win32 --arch=x64
--version=1.2.0`

In that case, my application was in the directory "helloworld" inside the executing directory.

**Comment by malept** [comment]
Since the original issue reporter has not responded to the request for additional information in about two weeks, I'm going to assume that they either found the answer in another manner or decided not to pursue this issue. If I'm incorrect, they can respond with answers to the questions posed, and I'll reopen.
