### ISSUE TITLE
packaged app fails to run on mac with error "Library not loaded: @rpath/libnode.dylib"

### ISSUE THREAD

**Issue by thecoderok** [electron-userland/electron-packager#379]
I am trying to use electron & electron packager for the first time. 
I built my app from Windows, generated versions for Mac & Win.
Windows version works fine, but app fails to run on Mac.

I am getting error "Library not loaded: @rpath/libnode.dylib"

Mac OS X 10.10.5 (14F27)

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000002, 0x0000000000000000

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @rpath/libnode.dylib
  Referenced from: /Users/vganzha/Desktop/tableau-webclient-metrics-parser-darwin-x64/tableau-webclient-metrics-parser.app/Contents/Frameworks/Electron Framework.framework/Electron Framework
  Reason: image not found

electron-packager version is 7.0.2
Electron version: 1.1.3

my package.json:

```
{
  "name": "tableau-webclient-metrics-parser",
  "version": "1.0.0",
  "description": "Display webclient metrics in more user-friendly format",
  "main": "main.js",
  "scripts": {
    "start": "electron main.js"
  },
  "devDependencies": {
    "electron-prebuilt": "^1.1.2"
  },
  "dependencies": {
    "mustache": "^2.2.1"
  }
}

```

**Comment by malept** [comment]
This is a good issue to provide a minimal testcase (an easy way to do so is to base it off of [electron-quick-start](https://github.com/electron/electron-quick-start)) so that other people can see if they can reproduce it.

That being said, I'm not convinced that we should be allowing Mac apps to be built on Windows...it only works under very specific conditions.

**Comment by thecoderok** [comment]
thanks, let me try to build it under mac. Will inform about result.

**Comment by thecoderok** [comment]
thank you, I built it on Mac and it works now!

**Comment by fortinmike** [comment]
@malept Are you allowing it or not? Currently (to my knowledge) nothing indicates that this scenario isn't possible. Building Windows apps on Mac is supported (with Wine), so... That's a bummer because adding additional Mac build agents to our CI server is not a workable solution for us at the moment, and I suppose that's true for others as well.

I assumed that the Electron container was already built and linked properly and that the app was just "dropped" in the appropriate folder when packaging, making it work on Windows without any of the usual Mac build toolset. Am I mistaken in how this works?

What are the "very specific conditions" required to make this work?

**Comment by malept** [comment]
It's allowed. In the past two years since this bug was opened, I didn't disable cross-platform building. *However*, due to weird interactions with things like permissions, it may not work the way you'd expect when the host is Windows and the target is not Windows. To my knowledge, you should be able to build for all platforms on Linux hosts.

Examples of problems building non-Windows targets on Windows hosts: #115, #164, #431

Please note that **all** of this is predicated on the condition that you are not using **any** native modules. If your Electron app requires native modules to run, due to Node limitations, you **must** have the same host and target platforms (and possibly arch, I can't remember at the moment) the same (i.e., build Windows targets on Windows hosts, Mac targets on Mac hosts, Linux targets on Linux hosts).

**Comment by fortinmike** [comment]
Thanks for the info (and the links to other relevant issues), I'll take a look at them. For the record, our app is quite simple and uses no native modules. We get the exact error mentioned by the OP (libnode.dylib).

**Comment by malept** [comment]
Unfortunately I don't own a Mac, so I can't debug this issue. What I would suggest is building the same Mac target app on both a Windows host and a Mac host, and look at the differences on a Mac.

**Comment by fortinmike** [comment]
Thanks for the suggestion, I'll see if I can find some time to do it and will report on my findings here if appropriate.
