### ISSUE TITLE
ubuntu no icon

### ISSUE THREAD

**Issue by strongant** [electron-userland/electron-packager#394]
var iconPath = __dirname + '/app/assets/img/appledisk.png';

function createWindow() {
  mainWindow = new BrowserWindow({
    width: 1000,
    height: 1000,
    icon: iconPath
  });

when electron start, i see nothing. 
![tes png](https://cloud.githubusercontent.com/assets/7685936/15998662/a9aa5322-3172-11e6-9ea5-fe1398314c05.png)

**Comment by malept** [comment]
See https://github.com/electron-userland/electron-packager/issues/90#issuecomment-225498415 and reply here.

**Comment by malept** [comment]
According to the [`BrowserWindow` documentation](http://electron.atom.io/docs/api/browser-window/), the `icon` argument needs to be a [`NativeImage`](http://electron.atom.io/docs/api/native-image), not a path string.

Since this question isn't related to electron-packager, I'm marking it as invalid and closing it.

**Comment by develar** [comment]
Use electron-builder to build deb/rpm/etc for Linux — icons will be installed according to https://developer.gnome.org/integration-guide/stable/desktop-files.html.en

**Comment by malept** [comment]
Creating a `.desktop` file shouldn't be necessary for setting an icon - it certainly doesn't for GNOME3. If it's required for Unity, I would be surprised.

**Comment by Autre31415** [comment]
I don't understand why a .desktop is necessary now. In pre 1.0 Electron linux icons worked and now they don't. I don't understand what changed and why.
