### ISSUE TITLE
build electron project for arm target

### ISSUE THREAD

**Issue by miladsajjadi** [electron-userland/electron-packager#397]
I am beginner in electron packager. i want to build my project for target arch arm v7. what should i do?
running this:
> electron-packager . MYPROJECT --platform=linux --arch=armhf --overwrite --prune
will cause in:
Unsupported arch armhf; must be one of: ia32, x64

my host machine is windows. does electron packager add support for arm build?

**Comment by malept** [comment]
electron-packager does not currently support armhf mostly because we've been waiting for Electron upstream to update their build system to say precisely which ARM architecture they support (for example, what happens when they add support for ARM v8?). This has been tracked in #107 and https://github.com/electron/electron/issues/2343
