### ISSUE TITLE
--osx-sign parameter makes the app freeze

### ISSUE THREAD

**Issue by azer** [electron-userland/electron-packager#419]
If I package my app passing --osx-sign parameter, it freezes when opening. Without this parameter, it works perfectly.

> Which version of electron-packager are you using?

7.0.4

> What CLI arguments are you passing? Alternatively, if you are using the API, what parameters are
> you passing to the `packager()` function?

electron-packager ./electron-app --platform=mas --arch=x64 --version="1.0.0" --asar --overwrite --app-bundle-id="abc" --app-category-type="public.app-category.games" --icon="./electron-app/logo.icns" --ignore="…" --app-version="1.3.2"

> What version of [Electron](http://electron.atom.io) are you building with?

1.2.4

> What is the host platform are you running electron-packager on?

OSX

**Comment by malept** [comment]
It looks like you're building with Electron 1.0.0, not 1.2.4.

Could you please show the `osx-sign` parameter that you're using as well?

CC: @sethlu

**Comment by malept** [comment]
Since the original issue reporter has not responded to the request for additional information in over two weeks, I'm going to assume that they either found the answer in another manner or decided not to pursue this issue. If I'm incorrect, they can respond with answers to the questions posed, and I'll reopen.
