### ISSUE TITLE
process.execPath times out on spawnSync call after packaged

### ISSUE THREAD

**Issue by gdurastanti** [electron-userland/electron-packager#430]
Using urllib-sync to do web requests and when packaged it looks like process.execPath is timing out on the packaged executable. It is being run with spawnSync, and is fine if the application is launched as electron from command line. However, for some reason the packaged process can't spawn another child process. If i hard code the execPath to my local electron exe everything works as expected. 

Any ideas?

> Which version of electron-packager are you using?

7.3.0

> What CLI arguments are you passing? Alternatively, if you are using the API, what parameters are
> you passing to the `packager()` function?

> What version of [Electron](http://electron.atom.io) are you building with?

1.2.6

> What is the host platform are you running electron-packager on?

Windows 10 x64

> What target platform(s)/architecture(s) are you building for?

win32 x64

> Is there a stack trace in the error message you're seeing?

{ Error: spawnSync C:\APP\App.exe ETIMEDOUT
    at exports._errnoException (util.js:949:11)
    at Object.spawnSync (child_process.js:460:20)
    at request (C:\APP\resources\app\node_modules\urllib-sync\index.js:33:16)
    at global.wrequire (C:\APP\resources\app\node_modules\wrequire\app.js:13:9)
    at startActivityEngine (C:\APP\resources\app\main.js:54:14)
    at _fulfilled (C:\APP\resources\app\node_modules\q\q.js:834:54)
    at self.promiseDispatch.done (C:\APP\resources\app\node_modules\q\q.js:863:30)
    at Promise.promise.promiseDispatch (C:\APP\resources\app\node_modules\q\q.js:796:13)
    at C:\APP\resources\app\node_modules\q\q.js:604:44
    at runSingle (C:\APP\resources\app\node_modules\q\q.js:137:13)
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'spawnSync C:\\APP\\App.exe',
  path: 'C:\\APP\\App.exe',
  spawnargs:
   [ 'C:\\APP\\resources\\app\\node_modules\\urllib-sync\\request.js',
     'eyJ1cmwiOiJodHRwczovL2Rldi1ycGNvbXMucHJvbWV0cmljLmNvbTo4NDQzL0FjdGl2aXR5RW5naW5lL2FwcC5qcyIsImFyZ3MiOnt9fQ==' ],
  url: 'http://pathtoapp/app.js',
  args: {} }

> Please provide either a failing testcase or detailed steps to reproduce your problem.

Call child_process.spawnSync on process.execPath after packaged.

**Comment by malept** [comment]
Try having different relative paths based on whether it's packaged or not? I imagine relative paths work differently because the source code is in different places depending on whether the app is packaged or not, so `__dirname` won't be the same. But I don't know what your `spawnSync` call looks like.

Out of curiosity, does an async spawn work the way you expect?

**Comment by malept** [comment]
Since the original issue reporter has not responded to the request for additional information in about two weeks, I'm going to assume that they either found the answer in another manner or decided not to pursue this issue. If I'm incorrect, they can respond with answers to the questions posed, and I'll reopen.
