### ISSUE TITLE
CLI hangs before packaging begins

### ISSUE THREAD

**Issue by babyChou** [electron-userland/electron-packager#470]
I'm trying to package `electron-quick-start` project in window 10.
it can run will in electron( electron . )
but when i try to package the project use command line.
there is no any reaction in terminal.

The following is my step

```
1. git clone https://github.com/electron/electron-quick-start
2. cd electron-quick-start
3. npm install electron -g
4. npm install electron --save-dev
5. npm install electron-prebuilt -g
6. npm install electron-prebuilt --save-dev
7. electron-packager . hello --ignore=node_modules/electron-* --platform=win32 --arch=x64 --version=1.0.2 
```

`My environment is window 10 with company proxy`

Is any step I go wrong?

**Comment by bampakoa** [comment]
@babyChou What version of **electron-prebuilt** and **electron-packager** are you using?

**Comment by malept** [comment]
@babyChou A few things, in addition to the questions asked above:

* Don't do steps 5 and 6. `electron` and `electron-prebuilt` are the same thing, and `electron-prebuilt` is deprecated (see the [Electron blog](http://electron.atom.io/blog/2016/08/16/npm-install-electron) for details).
* For that matter, it is unnecessary to install `electron` both globally *and* locally.
* You don't need to specify `--version` if you install the `electron` module.
* Per the [ignore documentation](https://github.com/electron-userland/electron-packager/blob/master/docs/api.md#ignore):
  * The ignore option you specified is unnecessary because by default it ignores the `electron`, `electron-prebuilt`, and `electron-packager` module directories.
  * If you choose to keep that option, you need to fix the syntax - `ignore` uses regular expression syntax, not glob syntax.
* Before step 7, run: `SET DEBUG=electron-packager`. There should be more output to determine why it's not working for you.

**Comment by babyChou** [comment]
@bampakoa The version of **electron-prebuilt** is 1.3.3 and **electron-packager** 7.7.0

**Comment by babyChou** [comment]
@malept 
I remove `electron-prebuilt` and run: `SET DEBUG=electron-packager`.
Then I run: `electron-packager . hello --platform=win32 --arch=x64` .
The following pictures are log. 
![image](https://cloud.githubusercontent.com/assets/7037478/17916773/e35cf3be-69e8-11e6-98ea-2abe44eb51b9.png)

After this command I add --version : `electron-packager . hello --platform=win32 --arch=x64 --version=1.3.3 `
![image](https://cloud.githubusercontent.com/assets/7037478/17916655/d9fbcb3e-69e7-11e6-8715-eb341e135d02.png)

and just hang here

**Comment by malept** [comment]
Oops, I should have been more specific. I should have said:

> You don't need to specify `--version` if you install the `electron` module **locally**.

If you install it locally (with `--save-dev`), it will read the Electron version from `package.json`.

> [...] and just hang here

That is an interesting problem. Can you run `SET DEBUG=electron-download,electron-packager,extract-zip` and rerun the command?

**Comment by bampakoa** [comment]
@babyChou I had the same problem and I experimented by installing all versions of electron-packager after 7.4.0. After that, I gave one more try with 7.7.0 and it worked. I never figured out why it worked like that. I hope this helps.

**Comment by babyChou** [comment]
@malept 
I followed your instructions 
install `electron` locally and run `SET DEBUG=electron-download,electron-packager,extract-zip`
It still not working
![image](https://cloud.githubusercontent.com/assets/7037478/17955467/09accea0-6ab5-11e6-99ec-39aa1af9e6e3.png)

Maybe I set something wrong in this computer that I don't know.
I would try another computer

**Comment by babyChou** [comment]
@bampakoa 
Thank you for your reply

**Comment by malept** [comment]
Yeah, at this point I'm not sure what the problem is. For some reason your installation of electron-packager is not making it to the "downloading Electron" stage. In the next release there will be some more debug statements that might help figure out what's wrong. If you would like to try it before we release the next version (I'm not quite sure when that will be), you should be able to run:

```shell
npm install -g electron-userland/electron-packager
```

and then rerun the `SET` and `electron-packager` commands from earlier.

**Comment by babyChou** [comment]
@malept 
Hi I try another computer and it work!!!
that  I use node version with v6.4.0

thanks for your help~~~

**Comment by albertkim** [comment]
I had this issue just now, resolved by updating Node to the latest version. I believe I was on 6.3.x and the package step was hanging.

**Comment by matt-shine** [comment]
Just had this issue also, tried reinstalling node, different node/npm versions, etc.

Found it was getting stuck on fs.remove(tempBase, cb) task.

Deleting ...\AppData\Local\Temp\electron-packager fixed it.
