### ISSUE TITLE
Electron-packager Not allowed to load local resource

### ISSUE THREAD

**Issue by danibuiza** [electron-userland/electron-packager#496]
When launching my app with electron there is no problems to do that:

`mainWindow.loadURL(`${__dirname}/../build/index.html`)
`
But when packaging it with electron-packager and launching the .exe file I get this error in the console:

`Not allowed to load local resource: file:///***/index.html (pointing to my index.html)`

**Comment by malept** [comment]
What does your app's file/folder structure look like?

**Comment by malept** [comment]
Since the original issue reporter has not responded to the request for additional information in about two weeks, I'm going to assume that they either found the answer in another manner or decided not to pursue this issue. If I'm incorrect, they can respond with answers to the questions posed, and I'll reopen.

**Comment by rkpatel33** [comment]
I am having  the same issue. The app runs fine when building for development but the path seems to fail when built with electron-packager.  Here is my file structure:

![image](https://user-images.githubusercontent.com/3799489/29744954-f288d44c-8a63-11e7-8acd-8b6531adb6fe.png)

And here is the way I create the path to my html file from the main render process:

![image](https://user-images.githubusercontent.com/3799489/29744931-9e47dd10-8a63-11e7-9b08-bc66c9aef147.png)

The full path build by the path.join function is:

```file:///Users/rishi/Projects/albert/albert-support-desktop/static/html/main-window.html```

And this is what `settings.project.root` returns:

```file:///Users/rishi/Projects/albert/albert-support-desktop```

Is there a correct way to build the path to project files?

**Comment by malept** [comment]
I don't know what `settings` is.

Typically what people do is use a relative path from `__dirname` (the directory of the current JS file), so you'd do something like `path.resolve(__dirname, '../../../static/html/main-window.html')`. _(Note that the number of `../`s might be different, it's hard to tell from a screenshot.)_

**Comment by rkpatel33** [comment]
`settings.js` exported a dict that looks like the below. I used `root: path.resolve('./')` with the single dot even though this file is one dir deep bc when running from `npm run` it seemed to resolve to where the npm command was run from, i.e. project root dir.  I guess this was causing issues in the build bc when I changed it to `root: path.join(__dirname, '../')`, everything worked fine.

![image](https://user-images.githubusercontent.com/3799489/29747582-fdc290f0-8ab3-11e7-9a39-2e090f643554.png)

More generally, I was wondering if there is a solution/setup where I can source everything  from paths relative to the project root dir (like require statements as well as path.join()'s) so that you don't have to worry about keeping paths  up to date if you just move a file to a diff directory. If I set up a global var and use that in a path join in a require statement like this:

```
require(path.join(global.PROJECT_ROOT + '/' + rootPath))
```

It breaks my Eslint and VS Code IntelliSense, I guess expectedly. In a Webpack setting this is possible but just not sure if it is in an Electron project setting.

Thx.
