### ISSUE TITLE
Using --out causes spawn /bin/sh ENOENT on Mac

### ISSUE THREAD

**Issue by sqwk** [electron-userland/electron-packager#499]
Using `electron-packager`with the `--out` option will produce a `spawn /bin/sh ENOENT` error. I am using node 6.5.0 on Mac OS 10.12.0.

I am using the following command inside my `package.json`: `electron-packager dist --darwin --out=dist --overwrite`

I have tried reinstalling, deleting node_modules, using `npm rebuild` and `npm cache clean`.

    Packaging app for platform darwin x64 using electron v1.4.1
    spawn /bin/sh ENOENT

**Comment by malept** [comment]
Thanks for filing an issue! In order to help you with your problem, we're going to need more information about it. In particular:

* Console output when you run electron-packager with the environment variable `DEBUG=electron-packager`. Please include the stack trace if one exists.

* Please provide either a failing minimal testcase (with code) or detailed steps to reproduce your
problem. Using [electron-quick-start](https://github.com/electron/electron-quick-start) is a good starting point.

**Comment by sqwk** [comment]
sqwk$ electron-packager dist --darwin --out=dist --overwrite
      electron-packager Electron Packager 8.0.0 +0ms
      electron-packager Node v6.5.0 +3ms
      electron-packager Host Operating system: darwin (x64) +1ms
      electron-packager Packager Options: {"_":["dist"],"all":false,"deref-symlinks":true,"download":{"strictSSL":true},"overwrite":true,"prune":true,"darwin":true,"out":"dist","dir":"dist","protocols":[]} +0ms
      electron-packager Target Platforms: darwin +1ms
      electron-packager Target Architectures: x64 +0ms
      electron-packager Inferring application name from productName or name in package.json +18ms
      electron-packager Inferring app-version from version in package.json +0ms
      electron-packager Inferring target Electron version from electron-prebuilt dependency or devDependency in package.json +2ms
      electron-packager Application name: test +0ms
      electron-packager Target Electron version: 1.4.1 +0ms
      electron-packager Ignored path regular expressions: +0ms [ '/node_modules/electron($|/)',
          '/node_modules/electron-prebuilt($|/)',
          '/node_modules/electron-packager($|/)',
          '/\\.git($|/)',
          '/node_modules/\\.bin($|/)' ]
      electron-packager Downloading Electron with options {"strictSSL":true,"platform":"darwin","arch":"x64","version":"1.4.1"} +373ms
    Packaging app for platform darwin x64 using electron v1.4.1
      electron-packager Creating /var/folders/tv/mlhq8zrd2wd4dt2dn13hmx440000gn/T/electron-packager/darwin-x64-template +6ms
      electron-packager Extracting /Users/sqwk/.electron/electron-v1.4.1-darwin-x64.zip to /var/folders/tv/mlhq8zrd2wd4dt2dn13hmx440000gn/T/electron-packager/darwin-x64-template +1ms
      electron-packager Initializing app in /var/folders/tv/mlhq8zrd2wd4dt2dn13hmx440000gn/T/electron-packager/darwin-x64/test-darwin-x64 from /var/folders/tv/mlhq8zrd2wd4dt2dn13hmx440000gn/T/electron-packager/darwin-x64-template template +2s
      electron-packager Ignored paths based on the out param: +3ms [ '/Users/sqwk/Sites/test/dist' ]
      electron-packager Running npm prune --production +6ms
spawn /bin/sh ENOENT

**Comment by malept** [comment]
Try running the following commands in the same directory as you run `electron-packager` and paste the output in this issue:

* `npm prune`
* `which npm`
* `type npm`

**Comment by malept** [comment]
Since the original issue reporter has not responded to the request for additional information in about two weeks, I'm going to assume that they either found the answer in another manner or decided not to pursue this issue. If I'm incorrect, they can respond with answers to the questions posed, and I'll reopen.
