### ISSUE TITLE
Unable to run electron app on another linux machine after packaging

### ISSUE THREAD

**Issue by Sam747** [electron-userland/electron-packager#504]
OS:Ubuntu
Electron:1.4.1
Node:4.0

Could not display “vplayer”.

There is no application installed for “executable” files. Do you want to search for an application to open this file

**Comment by malept** [comment]
Thanks for filing an issue! In order to help you with your problem, we're going to need more information about it. In particular:

* Console output when you run electron-packager with the environment variable `DEBUG=electron-packager`. This will tell us debug information about the system you are using to create the app bundle.

* What command line arguments are you passing? Alternatively, if you are using the API, what
parameters are you passing to the `packager()` function?

* How are you moving the app between Linux machines? Are you compressing the app bundle beforehand? If, so, with which command?

* Please provide either a failing minimal testcase (with code) or detailed steps to reproduce your
problem. Using [electron-quick-start](https://github.com/electron/electron-quick-start) is a good starting point.

**Comment by Sam747** [comment]
->   electron-packager /home/sam/Desktop/ed v5 --platform=linux --arch=x64 --asar=true
**Both machines are 64 arch**
->   Uncompressed form sharing on Network path
-> When I try to open app on another machine this error pop up

Could not display “vplayer”.
There is no application installed for “executable” files. Do you want to search for an application to open this file

Works perfectly on the same machine

**Comment by malept** [comment]
Does the protocol for your network mount (SMB, NFS, SSHFS ???) preserve file permissions?

I believe you can test this by placing `test.py` in the same folder as your app:

```python
#!/usr/bin/env python

print('hello world')
```

Run `chmod +x test.py` on the computer you ran `electron-packager` on, and then on the command line on the computer with the network mount, `cd` to that folder and run `ls -l test.py; ./test.py`. Paste the output here.

**Comment by malept** [comment]
Since the original issue reporter has not responded to the request for additional information in about two weeks, I'm going to assume that they either found the answer in another manner or decided not to pursue this issue. If I'm incorrect, they can respond with answers to the questions posed, and I'll reopen.

**Comment by michaelsogos** [comment]
Hi Sam747,

Did you find the way to resolve this issue?

**Comment by malept** [comment]
@michaelsogos if you could answer all of the questions I posed to the original reporter, that would help.
