### ISSUE TITLE
Windows binary build issue

### ISSUE THREAD

**Issue by 0x00A** [electron-userland/electron-packager#512]
On any version of `electron-packager`, when building a binary for `win32` / `x64` on `macOS`, i get the console error `%1 is not a valid Win32 application` after trying to run the app. This message relates to a native module ([leveldown](https://github.com/level/leveldown)), but seems to be the same error with any native module.

```
electron-packager . ${PRODUCT} \
  --platform=win32 \
  --arch=x64 \
  --version=${ELECTRON_VERSION:1} \
  --overwrite \
  --icon="${PROJECT}/static/icon.icns" \
  --out=./pkg \
  --ignore="${IGNORE}"
```

Any ideas what might case this?

**Comment by malept** [comment]
This is a limitation of the Node ecosystem rather than Electron Packager. In order to build Electron apps with native module dependencies, you need to be able to build the native module for the target platform/arch. Node (and by which I usually mean node-gyp) [does not currently support cross compilation](https://github.com/nodejs/node-gyp/issues/829) at the time of writing this comment. The workaround is to build apps on the same host platform as the target platform.
