### ISSUE TITLE
Allow cnpm to be used instead of npm on Windows

### ISSUE THREAD

**Issue by TooBug** [electron-userland/electron-packager#515]
cnpm is a replacement tool of npm which optimized the install speed. BTW, it uses a Chinese mirror by default.

The structure of node_modules is quite different when modules are installed with cnpm. (It uses some soft links.)

The installation of cnpm is:

```
npm install -g cnpm
```

When package apps, electron-packager hangs. The log stopped by this: 

```
electron-packager Ignored paths based on the out param: +3ms [ '/Users/TooBug/app-darwin-ia32',
  '/Users/TooBug/app-darwin-x64',
  '/Users/TooBug/app-darwin-armv7l',
  '/Users/TooBug/app-linux-ia32',
  '/Users/TooBug/app-linux-x64',
  '/Users/TooBug/app-linux-armv7l',
  '/Users/TooBug/app-mas-ia32',
  '/Users/TooBug/app-mas-x64',
  '/Users/TooBug/app-mas-armv7l',
  '/Users/TooBug/app-win32-ia32',
  '/Users/TooBug/app-win32-x64',
  '/Users/TooBug/app-win32-armv7l' ]
```

And the template folder of app is keeping increase, never stops.

I guess the problem occurs on the `npm prune` step.

related issue:  https://github.com/cnpm/npminstall/issues/155

**Comment by malept** [comment]
Does `cnpm prune --production` exist? If so, if  you modify Electron Packager to use that command instead of `npm prune --production`, does it still hang?

**Comment by TooBug** [comment]
Yes, cnpm do has the same `prune` command. How can I force electron-packager to use that command?

**Comment by malept** [comment]
Electron Packager needs to be changed to be able to specify a custom command as the package manager, in order to run the "prune `devDependencies`" command. (And also an `npm install` command in the testsuite.)

It should be called `packageManager` in the API, and `--package-manager` in the CLI. The default value should be `npm`. It should fail with a nice error message if the specified package manager either does not exist or is not an executable file.

**Comment by malept** [comment]
I am having a really difficult time getting cnpm to be called correctly on Windows, for some reason. Since Windows is not my area of expertise, I'm inclined to only implement cnpm support for Linux/macOS and wait for someone to file a PR to get this working correctly on Windows. It will raise an error if cnpm is selected on Windows in the meantime.
