### ISSUE TITLE
Using var electron = require('electron'); in index.html

### ISSUE THREAD

**Issue by juniordesenv** [electron-userland/electron-packager#522]
i'm trying to use Electron with angular-cli, however, when i build the .exe the variable  has set to undefined. On development environment its work normaly. 
i've tryed to import manually electron on .exe directory, but it's fail to send SendSync.

In my Index:
  <script>
    window.$ = window.jQuery = require('jquery');
    var electron = require('electron');
    document.write('<base href="' + document.location + '" />');
  </script>

in typings.d.ts:
declare var electron: any;

In component:
const {ipcRenderer} = electron;
console.log(ipcRenderer.sendSync('synchronous-message', 'ping'));

In package.json dependencies:
"@angular/common": "~2.1.0",
    "@angular/compiler": "~2.1.0",
    "@angular/core": "~2.1.0",
    "@angular/forms": "~2.1.0",
    "@angular/http": "~2.1.0",
    "@angular/platform-browser": "~2.1.0",
    "@angular/platform-browser-dynamic": "~2.1.0",
    "@angular/router": "~3.1.0",
    "ag-grid": "^6.2.1",
    "ag-grid-ng2": "^6.2.0",
    "bootstrap": "^3.3.7",
    "core-js": "^2.4.1",
    "jquery": "^3.1.1",
    "rxjs": "5.0.0-beta.12",
    "ts-helpers": "^1.1.1",
    "zone.js": "^0.6.23",
    "electron": "^1.4.5"

**Comment by ccnokes** [comment]
This is a little bit of a shot in the dark, but if angular-cli is bundling with webpack, you may need to add this to your webpack config: https://github.com/chentsulin/webpack-target-electron-renderer. Basically webpack rewrites all your `require`s to it's own internal version of require. Because webpack isn't bundling (nor could it) electron's modules, `ipcRenderer` is undefined. I think that package above makes it so that things like `require('electron')` aren't resolved by webpack's `require` function, it's left to node/Electron.

**Comment by juniordesenv** [comment]
put node Integration = false and worked! Thanks!
