### ISSUE TITLE
Unable to build an application for Raspberry Pi 3

### ISSUE THREAD

**Issue by rajuece** [electron-userland/electron-packager#535]
Using electron package manager am unable to build an application for the armv7a architecture i.e., Raspberry Pi 3 .. Does it support for this architecture..

**Comment by malept** [comment]
As of Electron Packager version 8.0.0, the `armv7l` architecture is supported. However, due to the way that ARM architectures identify themselves, you need to explicitly specify the `arch` parameter yourself.

**Comment by rajuece** [comment]
Yes I have seen **armv7l** architecture is supported . But Raspberry Pi 3 is raising an error that architecture not found when I specify the **--arch=armv7a** . And if I compile it using armv7l I am unable to run the application created.

**Comment by malept** [comment]
What is armv7a?

**Comment by rajuece** [comment]
It the processor present in Raspberry Pi 3 Model B which we are using. Is there any difference it shows for the both armv7a and armv7l. I don't know exactly.

**Comment by malept** [comment]
It's confusing because my Raspberry Pi 3 is running a stable Raspbian image, and when I run `uname -a` on it, it reports `armv7l`. However, according to Wikipedia it runs https://en.wikipedia.org/wiki/ARM_Cortex-A53 which is armv8, which is not currently supported by Electron.

The only architectures that Electron Packager supports is a subset of the architectures that Electron supports. All of the "Electron does not build/ for some version of ARM" issues seem to be getting merged into https://github.com/electron/electron/issues/259.

**Comment by rajuece** [comment]
On my raspberry pi 3 running on New Raspbian Pixel desktop when I run uname -a it shows Linux.

**Comment by malept** [comment]
Sorry, `uname -a` shows everything. I specifically meant `uname -m`.
