### ISSUE TITLE
asar unpack does not unpack files

### ISSUE THREAD

**Issue by Unforgiven-wanda** [electron-userland/electron-packager#543]
**Please describe your issue:**
Hello,
when using electron-packager programmaticaly, I wish to unpack the files inside a certain folder like so: 

```javascript
// other arguments
asar: {
      unpackDir: 'app/{server/*}',
      unpack: 'main.js'
    }
```

However, while the folder is indeed unpacked, the files inside it are not. I've tried specifying them by name in the `unpack` argument, but it seems it accepts only one file name.

I cannot use `server/**` because this folder contains subfolders I do not wish to unpack.

Any idea what's causing this?
Thank you.

PS: As an aside, quick question if you'll permit me: Is there some way to pack into asar only one specific folder, and have the rest unpacked?

**Comment by malept** [comment]
> I've tried specifying them by name in the `unpack` argument, but it seems it accepts only one file name.

`unpack` also takes a glob expression, perhaps try that.

> PS: As an aside, quick question if you'll permit me: Is there some way to pack into asar only one specific folder, and have the rest unpacked?

Doesn't look like it. I believe the only way to do it is to specify all of the folders you want unpacked via a glob in `unpackDir`, otherwise the folder structure may not be preserved. You may have to change the [`asar`](https://github.com/electron/asar) module if you don't want to use the workaround. (All of the `asar` options/operations are passed through to that module.)
