### ISSUE TITLE
"Unable to parse version string" via programmatic API

### ISSUE THREAD

**Issue by craxal** [electron-userland/electron-packager#552]
I believe "Unable to parse version string" is too vague of an error message. If I have the following options, you can see that `build-version` is the field with an incorrectly formatted version.

```js
{
    dir: ".artifacts/app",
    platform: "win32",
    arch: "ia32",
    out: ".artifacts/package",
    name: "MyApp",
    version: "1.3.1",
    "build-version": "private",
    "app-version": "0.8.7",
    icon: "icon",
    "app-bundle-id": "com.microsoft.MyApp",
    "helper-bundle-id": "com.microsoft.MyAppHelper",
    "version-string": {
        CompanyName: "MyCompany",
        LegalCopyright: "Copywrite (C) 2015 MyCompany. All rights reserved",
        ProductName: "My Application",
        FileDescription: "My Application",
        OriginalFilename: "MyApp.exe",
        InternalName: "MyApp"
    }
}
```

However, debugging output displays nothing helpful, and "Unable to parse version string" doesn't tell me which version string is bad, neither does it give the value it *did* try to parse.

This error message should be improved to tell me which property it was trying to parse and the value it received and tried to parse.

**Comment by malept** [comment]
Unfortunately, this error comes from rcedit, not Electron Packager. Could you please file a bug in the [rcedit issue tracker](https://github.com/electron/rcedit/issues)? (And link it here, if you could.)

We can't do anything actionable on this bug (other than possibly version bumping node-rcedit when that gets released, if it ends up being a minor release instead of a patch release), so I'm closing it.
