### ISSUE TITLE
Electron-packager windows icon not being updated

### ISSUE THREAD

**Issue by AhadCove** [electron-userland/electron-packager#557]
Im setting up my icon to my electron-packager cli, but its not working. I think theres some type of cache being saved somewhere. The icon is definitely working though. Whe I goto properties the icon is correct, but the main icon on the exe is showing the original electron app icon.

How can I change it heres the code im using for icon:

```
--icon=src/assets/icons/win/icon.ico
```

**Comment by malept** [comment]
My guess is that it's probably a caching issue. Try copying the already built EXE to a different machine.

**Comment by AhadCove** [comment]
Yeah, thats what I am thinking also. Okay I will try that

**Comment by domenkozar** [comment]
I also can't get it to work, it's always electron app icon.

**Comment by malept** [comment]
Just so I'm clear, when I say "caching issue", I mean some sort of built-in Windows icon cache.

My inclination is that this problem does not originate with Electron Packager. This is because Electron Packager passes all of the win32 target icon information verbatim to the [`node-rcedit` module](https://github.com/electron/node-rcedit). If it doesn't have to do with the Windows icon cache, then it's a bug either there or in [`rcedit`](https://github.com/electron/rcedit).

**Comment by englishextra** [comment]
@AhadCove 

use .ico not .png for windows
```
app.on("ready", function () {
	// create the window
	mainWindow = new BrowserWindow({
			width : 844,
			height : 640,
			icon : "favicon.ico",
			title : "My app"
		});`
```
If you launch electron ./index.js higher when www folder
=======
on windows for nwjs use .png icon, not .ico
and iindex.js says to launch
`mainWindow.loadURL("file://" + __dirname + "/www/index.html");`

you should have two same .ico:
./favicon.ico
./www/favicon.ico

That's for development

**Comment by malept** [comment]
@englishextra I'm not sure that's what the problem is.

**Comment by englishextra** [comment]
@malept It's not clear 
- is it already installed electron-packaged app
- or is it only compiled not packed into installer

**Comment by Sandon** [comment]
using .ico when instantiating a BrowserWindow works for me. Thanks, @englishextra

**Comment by evandrosimenes** [comment]
Copying the .exe to another windows pc the correct icon appears to me... confirming that @malept said above about icon caching...

**Comment by floating** [comment]
How can we force an icon update? Many users still seeing old icon even after updating to latest version.

**Comment by lmtoledo** [comment]
Hi, you can force the icon update by doing this:
1. Select the search box on the taskbar and type "Delete temporary files." Choose the "Delete Temporary Files" app from the list of results.
2. A window will open with 3 options to select, "Applications and features", "Others" and "Temporary files". You must choose "Temporary files".
3. You will see many options to erase data from your computer, you just have to select the option that says "thumbnails". After that, you must press the "Remove files" button.
4. You must get me out of Latin America.
 : ')

**Comment by englishextra** [comment]
```batch
@echo off
ie4uinit.exe -ClearIconCache
taskkill /IM explorer.exe /F
del /f "%localappdata%\IconCache_old.db" >nul 2>&1
move /y "%localappdata%\IconCache.db" "%localappdata%\IconCache_old.db"
cd "%localappdata%\Microsoft\Windows\Explorer\"
rmdir /q /s temp
mkdir temp
move /y "%localappdata%\Microsoft\Windows\Explorer\iconcache*" temp
echo "The system will now reboot. SAVE ALL WORK if you have not done so, then press Enter to continue."
pause
shutdown /r /t 0
echo this is a dummy line
```

**Comment by mouadessalim** [comment]
hey, not working for me, i am talking about icon in search box 
![image](https://user-images.githubusercontent.com/38190847/130235808-6ad95ee3-d0c0-48dc-9c8e-fa5ec017c6a7.png)
![image](https://user-images.githubusercontent.com/38190847/130236120-f669e05c-6e50-44e2-9d73-00f1177309ba.png)
but in application everything works fine, i've tried to install in another compturer and it's working but if i update the icon , windows 10 show me the last icon in the search box

**Comment by turbobuilt** [comment]
All right, I had this problem, cause for some reason I thought that ico was just an extension (like how mov and mp4 are basically interchangeable (i think 😄)).

But turns out if you just rename it, it will silently fail. To convert png to ico, download imagemagick, I think and run

```
convert icon.png -resize 256x256 icon.ico
```

Weird, but I asked chatgpt 4 for help, and I have to report it was so amazing.  In my log files, I had printed the buffer for the current icon, and it said this:

The issue might be related to the icon file format. The output mentions replacing an icon file with a buffer that starts with `89 50 4e 47`, which indicates a PNG file, not an ICO file.

I love chatgpt!
