### ISSUE TITLE
Data-toggles require double jQuery import

### ISSUE THREAD

**Issue by tobiasrm** [electron-userland/electron-packager#564]
**Problem**
I have a web app with several data-toggles, i.e. dropdown menus, toggle paragraph visibility etc.. They work fine in several browsers but are "non-functional" after packaging with electron. 
The error message says that jQuery is needed by bootstrap. 
I confirmed the issue by using the [w3c schools data toggle example.](http://www.w3schools.com/Bootstrap/bootstrap_collapse.asp) 

**More information and solution: electron forum**
I posted this issue [here](https://discuss.atom.io/t/problem-with-electron-packing-data-toggle-not-working/38518) on the electron forum, where you find images of the html source codes and the package.json.

I discovered the following workaround/solution: A double import of jquery seems solving the problem. It's strange but works. 

**Comment**
I use the current versions (2017-01-23). electron v.1.4.14 and electron-prebuilt v0.35.6
As I am an electron newby, I am not sure if the current electron fixes this problem but electron-prebuilt has it not yet integrated. However, I didn't this issue in any of the bug rackers before staring creating a new issue ticket.

**Source code for testing**
Please find the sources attached as .zip archive
[sources.zip](https://github.com/electron-userland/electron-packager/files/723469/sources.zip)

**Comment by MarshallOfSound** [comment]
@tobiasrm

`electron` and `electron-prebuilt` are actually the same package, you should only be using the `electron` package as of 1st Jan 2017.

In order to use jQuery in Electron you need to either

* Disable `nodeIntegration` on your BrowserWindow
* Or, install jquery locally and use `window.$ = window.jQuery = require('jquery');`

This is not an Electron or Electron Packager issue.  If you have any questions regarding using of Electron I would recommend directing them to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

**Comment by tobiasrm** [comment]
Works perfectly fine. Thanks a lot for your professional help.

**Comment by Kapilshanbhag09** [comment]
Thank bro because of you I could solved bootstrap js requires jquery issue in electron.
