### ISSUE TITLE
Packages linked with lerna are not compiled inside electron-packager

### ISSUE THREAD

**Issue by samb90** [electron-userland/electron-packager#567]
I have packages that are required in my electron project that are symlinked using lerna.

electron-packager does not copy these symlinked node modules into the built .app on Mac OSX.

**Comment by malept** [comment]
Have you tried using the [`derefSymlinks`](https://github.com/electron-userland/electron-packager/blob/master/docs/api.md#derefsymlinks) option? (`--deref-symlinks` if you're using the CLI)

**Comment by malept** [comment]
Since the original issue reporter has not responded to the request for additional information in over two weeks, I'm going to assume that they either found the answer in another manner or decided not to pursue this issue. If I'm incorrect, they can respond with answers to the questions posed, and I'll reopen.
