### ISSUE TITLE
Specify an output directory

### ISSUE THREAD

**Issue by dannystaple** [electron-userland/electron-packager#570]
It would be a useful enhancement to have some kind of --outdir parameter to specify an output directory, and the packages written there.

This makes sense so git, ide's and other tools can be configured to ignore this.

**Comment by MarshallOfSound** [comment]
@dannystaple Check out the docs for the CLI

You can use `--out` to specify the output directory.

https://github.com/electron-userland/electron-packager/blob/master/usage.txt#L50

Or if you are using the JS API you can use the `out` property

https://github.com/electron-userland/electron-packager/blob/master/docs/api.md#out

**Comment by patricknelson** [comment]
Took me a while to find this. I, like most people, am quite lazy and usually just CTRL+F to find the option. Maybe we could sprinkle in "directory" and/or "output" or even "destination" into that part of the document? Right now none of those words trigger and you'd have to find it from a ticket like this due to the keywords, or, actually being forced to read (gasp).

**Comment by malept** [comment]
The word "output" *does* exist exactly once in the API docs, in the docs right below the `out` parameter. The word "directory" is in the description of the `out` parameter twice.

That being said, it is a fair point that the documentation for `out` could be better, and I would welcome someone submitting a PR to reword it (and also add some explanation that the `out` parameter becomes part of the `ignore`d directories, if it's not the same as the application directory).

**Comment by patricknelson** [comment]
Right @malept  I see. Yes it does exist, however I suppose the problem is just that it's under a different option. Plus the formatting is not very easy to read. While that's not the main reason why I didn't find this option, it did contribute. Also note that this is coming from a relatively new user, so I may not be the only person who may encounter the same difficulty.
