### ISSUE TITLE
A module is not found on Windows

### ISSUE THREAD

**Issue by KamyarGhajar** [electron-userland/electron-packager#576]
I have packaged my project with electron 1.5.0 and The packaged app works fine on macOS but on windows the same packaged app, in a js file it can not use `require` from node js `module` to find something like this:
`const ab_service = require('../../../common/services/ab_service')`
and on windows the console show this error: 
```
Uncaught Error: Cannot find module '../../../common/services/ab_service'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (\\Mac\Home\Desktop\APP-win32-x64\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at file://mac/Home/Desktop/APP-win32-x64/resources/app.asar/src/renderer/modules/main/main.js:3:29
```

**Comment by KamyarGhajar** [comment]
BTW i'm running windows on Parallels 12 on macOS Siera

**Comment by malept** [comment]
In order to debug your problem further, we need a minimal testcase to reproduce your problem. Using the [`electron-quick-start`](https://github.com/electron/electron-quick-start) repository as a base, could you please create a minimal Electron app that illustrates the issue you described, and post a link to it here?

**Comment by malept** [comment]
Since the original issue reporter has not responded to the request for additional information in about two weeks, I'm going to assume that they either found the answer in another manner or decided not to pursue this issue. If I'm incorrect, they can respond with answers to the questions posed, and I'll reopen.

**Comment by stroborobo** [comment]
@malept @KamyarGhajar This is an issue with Parallels' shared folders, if you copy the output to local disk it'll work. Visual Studio for example also has some problems if you're working in shared folders, so this is not an electron-packager issue.

**Comment by KamyarGhajar** [comment]
Thanks @stroborobo
