### ISSUE TITLE
packaged app can't find `config.json` file

### ISSUE THREAD

**Issue by choxi** [electron-userland/electron-packager#585]
I have a `config.json` file that I read into my app that works fine during development, but I get a "not found" error whenever I try to use electron-packager and run the application. I created a fork of electron-quick-start here that reproduces the error: https://github.com/choxi/electron-quick-start

To reproduce:

1. Clone the repo, which just adds a `config.json` file and attempts to read it in `main.js`.
2. Run: `electron-packager . test --platform=darwin --overwrite"
3. Run: `open test-darwin-x64/test.app`

The error output I get on open is: 

![screenshot](https://i.imgur.com/2dNa57m.png)

I didn't see anything in the docs that suggested a `config.json` file would be ignored by the packager. I've also tried setting `--asar=false` to skip the asar processing, but I get the same message. Any help would be appreciated, thanks!

**Comment by MarshallOfSound** [comment]
@choxi Your issue is your usage of relative paths.

```js
./configA.json
```

Relative paths in node.js are by default resolved relative to your current working directory.  In dev mode this is normally where you would expect (root of your app).  In prod mode it is not.  You should always use `__dirname` to resolve file paths relative to the current files location.  E.g.

```js
const path = require('path');

const pathToFile = path.resolve(__dirname, 'configA.json')
```

**Comment by choxi** [comment]
Thank you for the quick response! You were right, specifically I started o use Electron's `app.getAppPath` function to construct the path to my config file and it works fine.
