### ISSUE TITLE
Electron packaging error

### ISSUE THREAD

**Issue by sreekumari** [electron-userland/electron-packager#588]
![error](https://cloud.githubusercontent.com/assets/19853138/23009084/cdb57c92-f3c8-11e6-8c3a-eec126107471.png)
When we package an angular2 app with electron we get the above error
Please post if any solutions

**Comment by malept** [comment]
My first instinct is that the `main` key in package.json is set to `index.js` but you named the entry point script something else.

**Comment by sreekumari** [comment]
its running as a electron app without packaging.but when packaged we are getting the error

**Comment by malept** [comment]
In order to debug your problem further, we need a minimal testcase to reproduce your problem. Using the [`electron-quick-start`](https://github.com/electron/electron-quick-start) repository as a base, could you please create a minimal Electron app that illustrates the issue you described, and post a link to it here?

**Comment by sreekumari** [comment]
thanks for your suggession.my file name for electron was main.js .while
packaging with webpack.it was packaged into an internal directory.copied it
to root and then addded main into package.json as"main":"main.js".solved
the problem.

One suggestion seen was while packaging electron and angular Keep angular
related contents in the root.main.js and angular stuff into some src etc..

On Feb 16, 2017 10:13 PM, "Mark Lee" <notifications@github.com> wrote:

In order to debug your problem further, we need a minimal testcase to
reproduce your problem. Using the electron-quick-start
<https://github.com/electron/electron-quick-start> repository as a base,
could you please create a minimal Electron app that illustrates the issue
you described, and post a link to it here?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/electron-userland/electron-packager/issues/588#issuecomment-280385896>,
or mute the thread

**Comment by malept** [comment]
You may be better off using [Electron Forge](https://github.com/electron-userland/electron-forge) instead of hand-rolling your own Electron app build system using webpack and Electron Packager. At the time of this comment, there's really only one reason to use webpack with Electron apps, it's documented [here](https://gist.github.com/malept/6df0c55fbca5438e25ff4e22ae123cee).
