### ISSUE TITLE
 npm run build

### ISSUE THREAD

**Issue by awdal-code** [electron-userland/electron-packager#592]
```
17 error Windows_NT 10.0.14393
18 error argv "F:\\nodejs\\node.exe" "F:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
19 error node v7.5.0
20 error npm  v4.1.2
21 error code ELIFECYCLE
22 error awdal-app@0.1.0 build: `electron-packager . --all . --platform-win32 --arch-x64`
22 error Exit status 1
23 error Failed at the awdal-app@0.1.0 build script 'electron-packager . --all . --platform-win32 --arch-x64'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the awdal-app package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     electron-packager . --all . --platform-win32 --arch-x64
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs awdal-app
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls awdal-app
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

**Comment by awdal-code** [comment]
not run

**Comment by malept** [comment]
There are a few problems with the command line for your `build` script:

* You have two `.`s, that makes it so that the name of your app is `.`, which I assume is incorrect.
* You specified both `--all` *and* a specific arch/platform combination. They are meant to be mutually exclusive.
* `--platform-win32` and `--arch-x64` are not valid parameters. Assuming you remove `--all`, they should be `--platform=win32` and `--arch=x64`, respectively. Please note that the hyphen was replaced with an equals sign.

**Comment by awdal-code** [comment]
Thanks a million. I really appreciate it.

**Comment by malept** [comment]
By the way, in the future, you should run the command outside of `npm run` to see what error messages are printed out the next time you have this kind of problem, because `npm run` does not show any of those errors. (It is a really annoying limitation of NPM.)

**Comment by awdal-code** [comment]
I'm a rookie!
