### ISSUE TITLE
Cloud Storage Keyfile.josn not packaging 

### ISSUE THREAD

**Issue by Mathi05** [electron-userland/electron-packager#620]
Hi,
 I developed an app for file upload to Google cloud storage. In local app works perfectly. But after packaging the app it throws an error(keyfile.json) file not found. 

**Code:**
var gcs = storage_google({
					projectId: 'test-account',
					keyFilename: './keyfile.json'
					});

Error:

Error: Cannot find module
appname\keyfile.json

Please help me out.

Thanks,

**Comment by MarshallOfSound** [comment]
@Mathi05 This is because you are using a relative path to get your keyfile.json.  Relative paths are relative to the CWD of the process that launched Electron.  In development this is normally where you expect (the root of your app) but in a packaged app this could be anywhere.

All paths in your app should use `path.resolve(__dirname, 'relative', 'path')` to determine the path to another file.  Your code should become.

```js
const path = require('path');

var gcs = storage_google({
projectId: 'test-account',
keyFilename: path.resolve(__dirname, 'keyfile.json'),
});
```

**Comment by Mathi05** [comment]
@MarshallOfSound  

Thank you, dude. Working fine!
