### ISSUE TITLE
How to build libnode.so shared library statically so it doesn't have to be distributed as well in Linux?

### ISSUE THREAD

**Issue by cirosantilli** [electron-userland/electron-packager#628]
`electron-quick-start` 1a4fd86f69d274c975ebd21b868d65d47e95224b
, Ubuntu 16.10, node v6.10.1, all works perfectly:

```
electron-packager . hello
./hello-linux-x64/hello
```

However, if I move hello elsewhere, it cannot find `libnode.so`:

```
$ mv ./hello-linux-x64/hello /tmp
$ /tmp/hello 
/tmp/hello: error while loading shared libraries: libnode.so: cannot open shared object file: No such file or directory
```

Dos this mean that to distribute the executable, I'd have to send two files, `hello` and `libnode.so`? That would be inconvenient.

**Comment by malept** [comment]
> Dos this mean that to distribute the executable, I'd have to send two files, hello and libnode.so?

In order to distribute an Electron app, you need to distribute all of the files in the `out` directory. You can't really change that sort of thing in Electron Packager. *If* that were to happen, and that's a big *if*, this would need to happen in the [upstream Electron project](https://github.com/electron/electron).
