### ISSUE TITLE
[UNKNOWN PROPERTY] issue

### ISSUE THREAD

**Issue by jdhydra** [electron-userland/electron-packager#634]
* [Y] I have read the [contribution documentation](https://github.com/electron-userland/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [Y] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [Y] I have searched the issue tracker for an issue that matches the one I want to file, without success.

**Please describe your issue:**
Hello. I just downloaded electron packager and i runned the command
`electron-packager ./ Client --platform=win32 --icon=icon.ico`
and i ran it. I've used this tool before but instead of the output, it said that "Unable to determine [UNKNOWN PROPERTY]. Please specify a [UNKNOWN PROPERTY].

I've gotten this error and i've looked at everything for about ~20 to ~30 minutes. I didn't find anything, help!

**Console output when you run electron-packager with the environment variable `DEBUG=electron-packager`. Please include the stack trace if one exists.**

```
Unable to determine [UNKNOWN PROPERTY]. Please specify a [UNKNOWN PROPERTY]
```

**What command line arguments are you passing? Alternatively, if you are using the API, what
parameters are you passing to the `packager()` function?**

```
./ Client --platform=win32 --icon=icon.ico
```

**Please provide either a failing minimal testcase (with a link to the code) or detailed steps to
reproduce your problem. Using [electron-quick-start](https://github.com/electron/electron-quick-start)
is a good starting point.**

**Comment by malept** [comment]
Thanks for filing an issue! In order to help you with your problem, we're going to need more information about it. In particular:

* Console output when you run electron-packager with the environment variable `DEBUG=electron-packager`, for example `DEBUG=electron-packager electron-packager ./ Client --platform=win32 --icon=icon.ico` on macOS or Linux.

* Please provide either a failing minimal testcase (with code) or detailed steps to reproduce your
problem. Using [electron-quick-start](https://github.com/electron/electron-quick-start) is a good starting point. Alternatively, please provide your `package.json` file.

**Comment by jdhydra** [comment]
Will do. The testcase is something i cannot provide, due to my computer causing the error, and yours wouldn't be able to replicate.

**Comment by malept** [comment]
Since the original issue reporter has not responded to the request for additional information in about two weeks, I'm going to assume that they either found the answer in another manner or decided not to pursue this issue. If I'm incorrect, they can respond with answers to the questions posed, and I'll reopen.
