### ISSUE TITLE
Application can not works in SUSE11.4

### ISSUE THREAD

**Issue by JasonyenChang** [electron-userland/electron-packager#653]
After build application through electron-packager, application works fine in Linux most distribution except SUSE11.4
How can I build an application apply on SUSE11.4?

**Comment by malept** [comment]
According to the [Electron documentation](https://electron.atom.io/docs/tutorial/supported-platforms/#linux), Electron releases are built with an Ubuntu 12.04 image.

I don't know whether you're referring to "SUSE Linux Enterprise 11.4" or "openSUSE 11.4", but if it's the second one, it will probably not work because it's too old (released in March 2011).

At any rate, platform compatibility questions like this are more suited for the [upstream Electron issue tracker](https://github.com/electron/electron/issues), because Electron Packager doesn't control what the platform requirements are, it just takes the existing upstream binary and customizes it.

**Comment by AbinayaDevarajan** [comment]
@malept ,
Did anyone attempt the build for SUSE enterprise 11.4? what is the actual issue that forbids the build?

**Comment by malept** [comment]
Per my [earlier comment](https://github.com/electron/electron-packager/issues/653#issuecomment-302910627):

> platform compatibility questions like this are more suited for the upstream Electron issue tracker, because Electron Packager doesn't control what the platform requirements are, it just takes the existing upstream binary and customizes it.
