### ISSUE TITLE
Unable to use electron-packager

### ISSUE THREAD

**Issue by gameslayer** [electron-userland/electron-packager#655]
I've cd'd to the application folder than installed electron-packager in my application like I normally would via the sudo npm install electron-packager --save-dev command but when I go to build I get this error electron-packager: command not found

**Comment by MarshallOfSound** [comment]
Run `./node_modules/.bin/electron-packager`

**Comment by gameslayer** [comment]
Hmm why do I have to do that now? I use to just run electron-packager . exampleapplication --all --icon=icon.png --overwrite and it would build now I have to change it again and it needs sudo permission to put files into tmp? they really need to standarize this and stop changing things so much..

**Comment by gameslayer** [comment]
Damn it I can't build the windows version again because of npm issues... this whole thing with electron is a complete mess...

**Comment by MarshallOfSound** [comment]
@gameslayer I'm not sure what the combination of problems you are experiencing is but I'll just cover a few things quickly

> Hmm why do I have to do that now?

The `electron-packager` command will not be added to your path unless either

a) You install it globally with `npm i -g electron-packager`
b) You have a magical path setup that puts the `node_modules/.bin` folder in your path

> they really need to standarize this and stop changing things so much..

This hasn't changed **ever** and almost certainly never will

>  it needs sudo permission to put files into tmp

This is because from the sounds of it you have run `sudo npm install ....` this will create files with root only access / write permissions so everything from then on will also require sudo permissions, you should avoid using sudo unlesss it is actually required.

> this whole thing with electron is a complete mess...

🤷‍♂️ idk, everyone works great where I'm sitting 😆 


All this said, it sounds like you got your packager command working now 👍

**Comment by gameslayer** [comment]
Not trying to fight with you but it has changed because I just to do that command like that to build directly from the and it worked fine and shouldn't need to use sudo to build only to install software either npm or apt..

**Comment by MarshallOfSound** [comment]
@gameslayer If at any point it worked from your command line with no relative path to the installed executable you must have installed it globally at some point with `npm i -g electron`.

Closing out as the original issue has been solved 👍 (packager can now be executed)

**Comment by gameslayer** [comment]
fixed it by install electron-packager globally, weird tho I had installed in the node-modules folder in the application and it use to work fine on the older version, really annoying how things keep changing.

**Comment by gameslayer** [comment]
Also thank you that command does fix both issues :D

**Comment by MarshallOfSound** [comment]
> really annoying how things keep changing.

For the record, I literally can't say this enough **nothing has changed regarding how you execute electron-packager**, it is literally impossible for the following to be possible

```bash
npm i electron-packager
electron-packager
```

That will always throw a `command not found` error, that's how NPM has always installed binaries and that hasn't and won't change 👍

**Comment by gameslayer** [comment]
Okay thanks again for helping me
