### ISSUE TITLE
 Change the package resource path

### ISSUE THREAD

**Issue by tkggusraqk** [electron-userland/electron-packager#661]
* [x] I have read the [contribution documentation](https://github.com/electron-userland/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

**Please describe your issue:**
There is no way to specify the name of the file folder that is packaged instead of resources

**Comment by MarshallOfSound** [comment]
`resources` is a folder required by Electron in order to locate your `app` or `app.asar` file which contains your actual app code.

What exactly do you wish to specify?

**Comment by malept** [comment]
Since the original issue reporter has not responded to the request for additional information in about two weeks, I'm going to assume that they either found the answer in another manner or decided not to pursue this issue. If I'm incorrect, they can respond with answers to the questions posed, and I'll reopen.
