### ISSUE TITLE
stdout maxBuffer exceeded

### ISSUE THREAD

**Issue by ZweiZhao** [electron-userland/electron-packager#679]
`electron-packager ./ 'myapp1' --platform=darwin --arch=x64`
> Packaging app for platform darwin x64 using electron v1.6.11

**then**
> stdout maxBuffer exceeded...

#### any issues solve this?

**Comment by malept** [comment]
Thanks for filing an issue! In order to help you with your problem, we're going to need more information about it. In particular:

* Console output when you run electron-packager with the environment variable `DEBUG=electron-packager`. Please include the stack trace if one exists.

* Please provide either a failing minimal testcase (with code) or detailed steps to reproduce your
problem. Using [electron-quick-start](https://github.com/electron/electron-quick-start) is a good starting point.

**Comment by malept** [comment]
Since the original issue reporter has not responded to the request for additional information in about two weeks, I'm going to assume that they either found the answer in another manner or decided not to pursue this issue. If I'm incorrect, they can respond with answers to the questions posed, and I'll reopen.

**Comment by bengotow** [comment]
Hey folks I just ran into this as well and it's making it difficult for me to diagnose the underlying issue. It seems that when you call `child_process.exec` there's an implicit limit to the amount of output that the exec'd process can emit - by default 200kb (https://stackoverflow.com/questions/23429499/stdout-buffer-issue-using-node-child-process).

This happened after I enabled verbose logging on a bunch of stuff by setting `DEBUG=electron-download,electron-packager,extract-zip`. I think `electron-download` is taking a long time and emitting more than 200kb of `....`?

**Comment by malept** [comment]
What are the implications of increasing the limit? Does it increase the amount of memory Packager allocates? _(I don't have time to look into it right now and would appreciate it if someone else could.)_

**Comment by Nowaker** [comment]
Reported again in https://github.com/electron-userland/electron-packager/issues/734.

**Comment by malept** [comment]
Reopening since there's a potential solution in #734.

**Comment by Nowaker** [comment]
From #734:

Non-code workaround:

- `export NPM_CONFIG_LOGLEVEL=info` before calling electron-packager. This reduces the output of npm commands significantly. 

A better code-based workaround / provisional fix:

- The one proposed in a PR that was recently rejected: https://github.com/electron-userland/electron-packager/pull/614

Proper fix:

- `spawn` should be used for executing any commands. Otherwise, if the output is too long, packaging will always be prone to an error like `stdout maxBuffer exceeded` or `stderr maxBuffer exceeded`.

**Comment by malept** [comment]
I'm actually considering replacing this code entirely so that Packager doesn't call any package managers to prune, so this is not very high on my list of things to fix.
