### ISSUE TITLE
Packaged APP can't load any module

### ISSUE THREAD

**Issue by Matheus-Ribeiro95** [electron-userland/electron-packager#680]
Hello guys, i runned successfully "electron-packager" in my app, but the bundled files doesnt include any node module. So my app unuseful when packaged.

Used with ASAR.
Any idea?

Thanks adv.

**Comment by malept** [comment]
Thanks for filing an issue! In order to help you with your problem, we're going to need more information about it. In particular:

* Console output when you run electron-packager with the environment variable `DEBUG=electron-packager`.

* What command line arguments are you passing? Alternatively, if you are using the API, what
parameters are you passing to the `packager()` function?

* Please provide either a failing minimal testcase (with code) or detailed steps to reproduce your
problem. Using [electron-quick-start](https://github.com/electron/electron-quick-start) is a good starting point.

**Comment by Matheus-Ribeiro95** [comment]
Thanks for the help!

Issue solved using flag "--no-prune" in CLI.

**Comment by malept** [comment]
If `prune` was your problem, then you shouldn't put any module that is required when you  run your app in the `devDependencies` section of package.json.

**Comment by Matheus-Ribeiro95** [comment]
I did it first, then i changed correctly, but even so the packager was not doing it correctly.
So i deleted "package-lock.json" then installed modules again and now its working.
Thanks.
