### ISSUE TITLE
Change ProductName and CompanyName

### ISSUE THREAD

**Issue by JasonyenChang** [electron-userland/electron-packager#693]
I would like to change ProductName and CompanyName through electron-packager.
Is it legal?

**Comment by MarshallOfSound** [comment]
Electron is distributed under the [MIT License](https://github.com/electron/electron/blob/master/LICENSE and pretty much everyone changes those values already.  Interpret that how you will.

I'm being deliberately vague here because none of us are lawyers and anytime someone asks "is something legal" I've got to simply put the boilerplate answer.

> We are not lawyers, if you have legal questions, ask an attorney, not developers 👍
