### ISSUE TITLE
stdout maxBuffer exceeded.

### ISSUE THREAD

**Issue by Panhaiwei** [electron-userland/electron-packager#700]
Example:
[electron-quick-start](https://github.com/electron/electron-quick-start)

![image](https://user-images.githubusercontent.com/13009686/29255438-f9606fee-80d3-11e7-8fc8-05726064b2f6.png)

**Comment by malept** [comment]
Thanks for filing an issue! In order to help you with your problem, we're going to need more information about it. In particular:

* Console output when you run electron-packager with the environment variable `DEBUG=electron-packager`.

Additionally, `-all` is not a flag, it needs two dashes, like `--all`.

**Comment by malept** [comment]
A suggestion: try installing Yarn, and using the flag `--package-manager=yarn` (make sure you're using Electron Packager 8.7.0 or greater). This sounds like something that was reported in https://github.com/electron-userland/electron-packager/pull/614.

**Comment by Panhaiwei** [comment]
thank;

**Comment by Nowaker** [comment]
@malept I'm getting a similar error:

```
Fri, 29 Sep 2017 16:17:43 GMT electron-packager Pruning modules via: npm prune --production
stderr maxBuffer exceeded
```

This is really a problem electron-packager doesn't execute commands properly, that is, using `spawn` rather than `exec`.
