### ISSUE TITLE
how to use ‘--ignore’  ignore a array

### ISSUE THREAD

**Issue by eminoda** [electron-userland/electron-packager#706]
````
--app
| -dist
| -src
| -node_modules
| .....
````
I use "package:win": "electron-packager . --ignore=src,node_modules --prune=true --overwrite --platform=win32 --arch=ia32 --out=out --icon=favicon.ico"
but this result is ‘node_modules’ still exist.

**Comment by malept** [comment]
First, ignoring `node_modules` will likely cause your app to not work, because that's where everything in  your `dependencies` section of `package.json` is installed. By default, all of your `devDependencies` are removed when preparing your app.

Second, to ignore multiple things, you have two options:

1. Use the `--ignore` parameter multiple times
2. Use the `|` feature of regular expressions, because [as stated in the docs](https://github.com/electron-userland/electron-packager/blob/master/docs/api.md#ignore), `ignore` takes a [regular expression](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp).

**Comment by eminoda** [comment]
tks for your reply。
looked the api，u say prune can ignore node-module。
but in ‘electron quick start demo’ didnt work？
i tryed two ways：
`
"scripts": {
    "start": "electron .",
    "win": "electron-packager .  --ignore=src --ignore=e2e --overwrite --platform=win32 --arch=ia32 --out=out --icon=favicon.ico"  
}`

`
"scripts": {
    "start": "electron .",
    "win": "electron-packager . --prune=true --ignore=src --ignore=e2e --overwrite --platform=win32 --arch=ia32 --out=out --icon=favicon.ico"  
}`
but in **out** node-modules still have logger
http://chuantu.biz/t6/13/1503216794x1700615998.png

**Comment by eminoda** [comment]
i made a mistake. 
prune=false,the devDependencies & dependencies will generate
prune=ture,just dependencies

**Comment by eminoda** [comment]
here is my sample:git@github.com:eminoda/angular4-electron.git
````
npm run win
````
out/xx/node_modules,have another modules,i just think there are logger &log4js in node_modules

**Comment by malept** [comment]
A few things:

* Prune is enabled by default, you only have to specify it if you're disabling the feature.
* I still don't understand why you insist on ignoring the `node_modules` directory.
* You're putting *all* of your app's dependencies in `devDependencies` for some reason, which would result in your app not working when prune is enabled. See the NPM docs for when you should use `devDependencies`: https://docs.npmjs.com/files/package.json#devdependencies

**Comment by eminoda** [comment]
thanks a lot
