### ISSUE TITLE
Handling native extensions

### ISSUE THREAD

**Issue by rgbkrk** [electron-userland/electron-packager#72]
What's the best way to handle native extensions with electron packager?

In my case, I'm interested in building node-zmq which is causing me enough hassles as it is. Making sure that plays well on Windows, Linux, and Darwin is even more fun!

**Comment by tengyifei** [comment]
+1 Would also like to know if there is any convenient way of downloading and packaging native extensions.

**Comment by s-a** [comment]
Please check #95 and tell me what you think :eyes:

**Comment by malept** [comment]
At this point, the current recommended way is to use [electron-rebuild](http://electron.atom.io/docs/tutorial/using-native-node-modules/) and build the extensions on the same platform/arch that you're targeting. This is because as far as I can tell, Node (or rather, the node-gyp ecosystem) [does not currently handle cross-compilation](https://github.com/nodejs/node-gyp/issues/829).
