### ISSUE TITLE
Python path in packaged electron app

### ISSUE THREAD

**Issue by MonkeyChap** [electron-userland/electron-packager#724]
Hi,

Not sure if anyone can help with this as it may not be a bug, and what we're doing isn't exactly vanilla electron development.

Our electron app contains some Python scripts which we're calling from node using the python-shell module. It all works really well in dev mode (npm start) but fails in the packaged app. The reason seems to be that in dev mode, the Python path (sys.path in python) is pointing to the installed v3.6 Python path. In app mode, the path reverts to the default Apple Python install (v2.7) and so our modules won't load. 

Does anyone know why the packaged path ends up being different to the dev path ?  I realise this is a bit of an oddball request as very few electron apps package up python, but if any obvious culprits/workarounds spring to mind, I'd be really grateful.

PS - It's pretty much impossible to avoid having more than one version of Python on a Mac as 2.7 comes with the OS, and is used by the OS. If you need a more modern version, you have to install it in parallel, but most installs will change the default path to the latest. 

Many thanks

Ian

**Comment by malept** [comment]
For future reference, support questions are better off at [one of the community sites](https://github.com/electron-userland/electron-packager/blob/master/SUPPORT.md), as there are more people looking at those sites than this issue tracker.

Regarding your question, I would suggest doing something like creating a virtualenv that your Electron app operates in, so that you can avoid system-installed Python conflicts. _(Questions about virtualenv itself are off-topic for this issue tracker, though.)_

**Comment by MonkeyChap** [comment]
Thanks - I'd tried that. I'll pursue the community sites approach though.
