### ISSUE TITLE
Out of memory error

### ISSUE THREAD

**Issue by abdurrahmanekr** [electron-userland/electron-packager#729]
Hi, I'm using package.json file dependencies value's being null (like `dependencies: {}`). And node_modules directory 400mb and majority of the dependencies are `devDependencies`. But I'm running this code like below:
```json
{
    "scripts":{
        "pack:electron": "electron-packager . Project --platform=darwin --overwrite"
    }
}
```
following error of "Javascript out of Memory". By default I only know that dependencies are included. Why not no dependencies when there is include all node_modules?
Why all node_modules has been included although there is no dependencies. Could you help me in this issue?

nodejs: v6.10.2
npm: 4.2.0

**Comment by abdurrahmanekr** [comment]
Full error: 
```bash
Packaging app for platform darwin x64 using electron v1.6.13

<--- Last few GCs --->

  317738 ms: Mark-sweep 1292.5 (1439.4) -> 1292.4 (1439.4) MB, 1413.9 / 1.4 ms [allocation failure] [GC in old space requested].
  319152 ms: Mark-sweep 1292.4 (1439.4) -> 1292.4 (1439.4) MB, 1413.2 / 1.5 ms [allocation failure] [GC in old space requested].
  320635 ms: Mark-sweep 1292.4 (1439.4) -> 1300.5 (1423.4) MB, 1482.0 / 1.7 ms [last resort gc].
  322130 ms: Mark-sweep 1300.5 (1423.4) -> 1308.5 (1423.4) MB, 1495.0 / 1.5 ms [last resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

    2: arguments adaptor frame: 1->2
Security context: 0x193b667cfb39 <JS Object>
    3: oncomplete [fs.js:123] [pc=0x58a56e0d46f] (this=0x231fda938be1 <an FSReqWrap with map 0x197a5651b121>)
    4: arguments adaptor frame: 1->0

==== Details ================================================

[2]: arguments adaptor frame: 1->2 {
  // actual arguments
  [00] : 0xed01727d899 <an Error with map 0x197a56520819>
}

[3]: oncomplete [fs.js:123] [...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/usr/local/bin/node]
 2: node::FatalException(v8::Isolate*, v8::Local<v8::Value>, v8::Local<v8::Message>) [/usr/local/bin/node]
 3: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/usr/local/bin/node]
 4: v8::internal::Factory::NewFixedArray(int, v8::internal::PretenureFlag) [/usr/local/bin/node]
 5: v8::internal::TypeFeedbackVector::New(v8::internal::Isolate*, v8::internal::Handle<v8::internal::TypeFeedbackMetadata>) [/usr/local/bin/node]
 6: v8::internal::(anonymous namespace)::EnsureFeedbackVector(v8::internal::CompilationInfo*) [/usr/local/bin/node]
 7: v8::internal::(anonymous namespace)::GenerateBaselineCode(v8::internal::CompilationInfo*) [/usr/local/bin/node]
 8: v8::internal::(anonymous namespace)::GetUnoptimizedCodeCommon(v8::internal::CompilationInfo*) [/usr/local/bin/node]
 9: v8::internal::Compiler::Compile(v8::internal::Handle<v8::internal::JSFunction>, v8::internal::Compiler::ClearExceptionFlag) [/usr/local/bin/node]
10: v8::internal::Runtime_CompileLazy(int, v8::internal::Object**, v8::internal::Isolate*) [/usr/local/bin/node]
11: 0x58a569092a7
12: 0x58a56934338
13: 0x58a56909895
14: 0x58a56e0d46f
15: 0x58a56909895
16: 0x58a5693b7a3
Abort trap: 6
```

**Comment by malept** [comment]
Thanks for filing an issue! In order to help you with your problem, we're going to need more information about it. In particular:

* Console output when you run electron-packager with the environment variable `DEBUG=electron-packager`. Please include the stack trace if one exists.

* Please provide either a failing minimal testcase (with code) or detailed steps to reproduce your
problem. Using [electron-quick-start](https://github.com/electron/electron-quick-start) is a good starting point.

**Comment by WhoAteDaCake** [comment]
Having similar issue where usage goes up to 1.6GB RAM

**Comment by abdurrahmanekr** [comment]
I resolve the problem by deleting and reinstalling the node_modules folder. I guess I was doing a lot of work on the computer at that time and I was using memory. I could not catch that error again. But if it happens again I will share it here.

**Comment by malept** [comment]
Since the original issue reporter has not responded to the request for additional information in about two weeks, I'm going to assume that they either found the answer in another manner or decided not to pursue this issue. If I'm incorrect, they can respond with answers to the questions posed, and I'll reopen.

You can mitigate excessive memory usage by setting `packageManager: false` in API or `--no-package-manager`, because package managers use a fair amount of memory to prune.
