### ISSUE TITLE
Lerna + Scoped packages not being copied even with deref symlink

### ISSUE THREAD

**Issue by natew** [electron-userland/electron-packager#738]
Just ran into this rather weird one.

If you have packages that are scoped like: `@org/package` and then use lerna and those are symlinked into your electron app, electron-packager doesn't copy them even with derefSymlinks.

Working around this is tough if your entire lerna project uses scoped packages, because there are so many, so it's hard to just script it away.

**Comment by malept** [comment]
In order to debug your problem further, we need a minimal testcase to reproduce your problem. Using the [`electron-quick-start`](https://github.com/electron/electron-quick-start) repository as a base, could you please create a minimal Electron app that illustrates the issue you described, and post a link to it here?

**Comment by natew** [comment]
I managed to fix it by using `cpx` rather than `fs.copy` in the common.js file, so that sort of patch should work.

If I get a chance I'll spend the time to create a large app with lerna and custom scoped modules, but I think the problem/solution is well defined here.

**Comment by malept** [comment]
I'd prefer it if it was not a "large app", because then it eliminates as many variables as possible. I don't have much time these days to experiment with figuring out how to make minimal testcases out of issue reporters' descriptions, so if you could provide one, that would make it faster to debug and fix.

**Comment by natew** [comment]
I understand. What I'm explaining is the issue is pretty simple and completely isolated, it's just making a test-case is a bit harder because you have to symlink a scoped package, which means lerna, etc.

I can submit a PR that attempts to use cpx rather than fs.copy that may be easier.

**Comment by malept** [comment]
> I can submit a PR that attempts to use cpx rather than fs.copy that may be easier.

I don't particularly want to go that route yet. I'd like to avoid adding more dependencies if I can help it.

**Comment by natew** [comment]
For the record this is a legit one. I am still working around with cpx as it seems to copy deep symlinks better.

**Comment by walleXD** [comment]
@malept can you use the [repo](https://github.com/walleXD/react-universal) I am working with?

**Comment by malept** [comment]
I don't know how to use that repo, there aren't any instructions in the README. Am I supposed to do something in the top level dir first?

**Comment by walleXD** [comment]
Its a monorepo created with `lerna`. So, you need to globally install `lerna` and then in the root directory run `lerna bootstrap` to install all dependencies. Then you can run yarn scripts inside the desktop folder. So, `yarn package` will run `electron-packager` and should throw the error associated with missing `@react-universal/component` package

**Comment by malept** [comment]
I took a look at `cpx`, it's not feasible as a replacement because it doesn't have the `filter` functionality that [`fs-extra.copy`](https://github.com/jprichardson/node-fs-extra/blob/master/docs/copy.md) has.

**Comment by malept** [comment]
@walleXD I can build a bundled Electron app from your repository if I make these changes to it:

```diff
diff --git a/packages/desktop/package.json b/packages/desktop/package.json
index 22fea07..9323cf9 100644
--- a/packages/desktop/package.json
+++ b/packages/desktop/package.json
@@ -31,8 +31,8 @@
         ]
       },
       "electronPackagerConfig": {
-        "packageManager": "yarn",
-        "deferSymlinks": false
+        "packageManager": false,
+        "derefSymlinks": true
       },
       "electronWinstallerConfig": {
         "name": "desktop"
```

I also have to wipe out the ignores (you'd need to move the Forge config to a JavaScript file, per its README, and set `electronPackagerConfig.ignore` to `file => false`), because there's an interesting bug with the `pruner` module and the default set of ignores.

**Comment by natew** [comment]
Hm, so revisiting our builds today. Updated to the latest npm release. It's giving me this err:

```
ENOENT: no such file or directory, stat
```

When it runs into a symlink. But I'm using this config:

```
  const paths = await electronPackager({
    dir: ELECTRON_DIR,
    out: Path.join(ROOT, 'app'),
    icon: Path.join(ROOT, 'resources', 'icon.icns'),
    overwrite: true,
    // tmpdir: false,
    derefSymlinks: true,
    prune: false,
    packageManager: false,
  })
```

It seems unhappy with a symlink, but I do have derefSymlinks on. Checking more into it, going to try with pune: true.
