### ISSUE TITLE
Cannot use native modules when asar is enabled

### ISSUE THREAD

**Issue by JackieLs** [electron-userland/electron-packager#740]
Just Like the image.I run this in dev type is very ok. But When I package it, something go wrong....
![image](https://user-images.githubusercontent.com/14228179/31936320-d2ccd3ac-b8e3-11e7-9f3c-4b62d339b538.png)

**Comment by malept** [comment]
Thanks for filing an issue! In order to help you with your problem, we're going to need more information about it. In particular:

* Console output when you run electron-packager [with the environment variable `DEBUG=electron-packager`](https://www.npmjs.com/package/debug#usage). Please include the stack trace if one exists.

* What command line arguments are you passing? Alternatively, if you are using the API, what
parameters are you passing to the `packager()` function?

* What does your `package.json` look like?

* Please provide either a failing minimal testcase (with code) or detailed steps to reproduce your
problem. Using [electron-quick-start](https://github.com/electron/electron-quick-start) is a good starting point.

**Comment by JackieLs** [comment]
Sorry, so late to provide these info.
the config.
```
module.exports = {
	appVersion: pkg.version,
	arch: ['x64'], // ia32, x64, armv7l, all
	asar: true,
	dir: path.join(__dirname, '../app'),
	icon: path.join(__dirname, '../app/icons/icon'),
	ignore: /renderer/,
	out: path.join(__dirname, '../builds'),
	overwrite: true,
	platform: process.env.PLATFORM_TARGET,
	extraResource: [ 
		path.join(__dirname, '../app/mind/mind_darwin'), 
		path.join(__dirname, '../app/mind/mind_win32.exe')
	]
}
```
And I solved this problem after I remove the `asar: true` (default: false) opt on Windows.
I've read a lot of issue. Maybe this should not be the electron-packager's duty.
I'm not sure.But Windows is really confusing.
Thx.

**Comment by malept** [comment]
This is a known issue with asar and native modules, and also why I hesitate to make asar default to `true`.

**Comment by leozzyzheng** [comment]
I'm facing the same problem, I think the native module should be copied beside the asar file not the temp folder, and the require should be able to load the node module outside the asar file.

**Comment by leozzyzheng** [comment]
set `--asar.unpack=*.{node,dll}` in command line or set `asar: { unpack: '*.{node,dll}' }` in config object will do the trick.

**Comment by robosushie** [comment]
> set `--asar.unpack=*.{node,dll}` in command line or set `asar: { unpack: '*.{node,dll}' }` in config object will do the trick.

I tried the same config, but I am getting the same issue, but this time it is not referencing the temp folder.
Please check this [link](https://stackoverflow.com/questions/67757938/packaged-app-is-unable-to-locate-node-file-in-electron-forge)  for the details.

Thanks

**Comment by xmsz** [comment]
i want to hide the dll in app.asar
