### ISSUE TITLE
electron-packager should ignore the out directory

### ISSUE THREAD

**Issue by dominicrico** [electron-userland/electron-packager#742]
* [x] I have read the [contribution documentation](https://github.com/electron-userland/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

**Please describe your issue:**

Electron-packager should ignore the out directory by it self.

**Comment by malept** [comment]
According to the [NEWS file](https://github.com/electron-userland/electron-packager/blob/master/NEWS.md#600---2016-03-28), it has since v6.0.0:

https://github.com/electron-userland/electron-packager/blob/60aa780e054022f03338d28a829143d109c66f77/ignore.js#L35-L50

Is it not working for your application? If so, we're going to need more information about it. In particular:

* Console output when you run electron-packager with the environment variable `DEBUG=electron-packager`. Please include the stack trace if one exists.

* What command line arguments are you passing? Alternatively, if you are using the API, what
parameters are you passing to the `packager()` function?

* Please provide either a failing minimal testcase (with code) or detailed steps to reproduce your
problem. Using [electron-quick-start](https://github.com/electron/electron-quick-start) is a good starting point.
