### ISSUE TITLE
how to make it look for more.js instead of main.js

### ISSUE THREAD

**Issue by craigcosmo** [electron-userland/electron-packager#749]
How to direct packager to look fore more.js instead of main.js?

I have a file named main.js and it's listed in package.json as main:main.js . I do not want packager use that main file to pack thing. Is there way to make it look for more.js file instead?

**Comment by malept** [comment]
I'm assuming that `main.js` is used when you run your Electron app in development mode? If that's the case, you can use the [`afterCopy` hook](https://github.com/electron-userland/electron-packager/blob/master/docs/api.md#aftercopy) to manipulate the `package.json` file that will be packaged. Please note that you will need to use the API, rather than the command line, to use the hook.

**Comment by craigcosmo** [comment]
you got an example?

**Comment by malept** [comment]
I'd need some time to write it up. Basically in the `afterCopy` hook, read + parse the `package.json` file, set `main` to the relative location of `more.js`, and then write the serialized changes back to the same `package.json` file.

**Comment by craigcosmo** [comment]
still looking forward to your example

**Comment by malept** [comment]
I have limited time for F/OSS maintaining these days, I'm not sure when I'm going to get around to writing up a full code example. Is my description not enough to start with?

**Comment by valorize** [comment]
Another idea is
`"start": "NODE_ENV=development electron ."` in package.json

and in main.js
```
const main = process.NODE_ENV == 'development' ? require('development.js') : require('production.js');
```
