### ISSUE TITLE
Support Electron specified as a sub dependency

### ISSUE THREAD

**Issue by njbmartin** [electron-userland/electron-packager#750]
> **TLDR** Allow a child dependency to be responsible for the Electron version without implicitly having to include it in the parent dependencies.

One of our projects has a dependency (for simplicity, let's call it `common-electron`). It essentially contains common electron logic and packager logic used in a number of our projects to remove repetition and handle important features etc.

We should be able to set Electron as a dependency of `common-electron`, and simply set `common-electron` as a dependency of `project-one` and `project-two`.

```
Project One     Project Two
      \             /
     Common Electron
           |
        Electron
```

In order to support this, we could instead be inferring the version from `./node_modules/electron/package.json`.

This assumes that Electron has been installed via the project itself or one of its dependencies.

**Comment by malept** [comment]
I like the feature request as a concept. However, implementing this feature would require a significant reworking of how we infer Electron versions - we delegate to another module traversing directories and querying any `package.json` files it finds. Additionally, it would also incur a significant I/O performance cost, because we'd have to traverse the `node_modules` tree for each `package.json` directory we traverse to find the correct `electron`. One of the reasons why we would have to traverse (instead of just searching for `./node_modules/electron/package.json`) is because when you use `electron-prebuilt-compile` (which depends on `electron`), the installation of `electron` is actually in `node_modules/electron-prebuilt-compile/node_modules/electron`.

Given that the implementation/maintenance cost is high, a very small percentage of the userbase will use this feature, and that there's a workaround in the form of querying `node_modules/electron/package.json` yourself and using the JS API to call Electron Packager, I'm not inclined to implement this.
