### ISSUE TITLE
Can package to different asar?

### ISSUE THREAD

**Issue by keyiis** [electron-userland/electron-packager#793]
I want package my app source to two asar through electron-rebuild,this is possible?
![qq 20180125163342](https://user-images.githubusercontent.com/7766085/35378976-91c738c0-01ef-11e8-969f-55b932e79722.png)

**Comment by malept** [comment]
Sure, but you'd have to do it in an [`afterCopy` hook](https://github.com/electron-userland/electron-packager/blob/v10.1.1/docs/api.md#aftercopy) (requires use of the JavaScript API instead of the command line), and delete the files from the build path, so that the packager process doesn't put the `main.asar` files also in `app.asar`. You'd also have to invoke the `asar` module yourself both in the `afterCopy` hook and in your Electron app, so it knows to create and use `main.asar`, respectively.
