### ISSUE TITLE
How do I add a packaging format?

### ISSUE THREAD

**Issue by TobiasSN** [electron-userland/electron-packager#806]
* [ ] I have read the [contribution documentation](https://github.com/electron-userland/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [ ] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [ ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

As a developer for the Electron framework, I need to be able to package my applications for any platform that I want to distribute them on. For Windows and Mac, that's easy. But for Linux, while there's a few formats available for certain package managers, it's gonna be quite a pain to do it manually each time for any of the other ones. More specifically, the main one that isn't there that I want is pacman (Arch Linux).

So, either I'd like someone else to implement support for pacman, or, preferrably, to have better documentation that might help me do it myself, and make it easier for others to do the same for other package managers,.

Thank you in advance!

**Comment by malept** [comment]
I recently wrote the [`electron-installer-snap`](https://github.com/electron-userland/electron-installer-snap) module and am co-maintainer of a couple of the other Linux distributable creating modules for Electron, so I can answer the question about how they work.

`electron-installer-debian`, `electron-installer-redhat`, `electron-installer-flatpak`, and `electron-installer-snap` work by taking the output of Electron Packager (this repo), doing some transformations to get it in the right filesystem format, and generating the correct metadata. The binary that creates the distributable is then spawned.

To take `electron-installer-debian` as an example, it:
* gathers default options
* merges in the user-specified options (e.g., `src` is the packaged directory path, `dest` is the path to the created `.deb`)
* creates a temporary directory to stage the package
* creates the metadata (like `debian/control`) and the `.desktop` file in the staging directory
* copies the application into the staging directory
* runs `dpkg` to create the package
* moves the `.deb` to `dest`

From a technical perspective, ideally, to integrate with [Electron Forge](https://github.com/electron-userland/electron-forge), which uses Packager and all of the modules mentioned above internally, the module would return a Promise that would eventually return the path(s) to the created distributable(s).

Unfortunately, my free time is limited and I don't wish to take on yet another project to create another installer module, particularly for a distribution that I don't use. _(In fact, the only reason the Snap module came about was because Canonical sponsored the work.)_ But I would be happy to help other people create it. It appears that for pacman, you'd be wrapping the [`makepkg` command](https://wiki.archlinux.org/index.php/Makepkg).

**Comment by TobiasSN** [comment]
I think you misunderstood me there. I am well aware of how to make pacman packages. What I wanted to know is how to link up a module to electron-packager, as I want to contribute the code to this repo, for the purpose of making it easier for me and other people to just add something like "pacman" to their config file (If they use Electron Forge), instead of hassling with some new stuff that they never used before.

**Comment by develar** [comment]
@TobiasSN electron-builder is able to produce pacman packages and supports both electron-packager and electron-forge.

**Comment by TobiasSN** [comment]
Ah. Thanks!

**Comment by malept** [comment]
@TobiasSN just to be clear, you'd want to link a module to Electron Forge, not Electron Packager. Electron Packager is distributable-agnostic.

**Comment by malept** [comment]
@TobiasSN What I described in how `electron-installer-debian` in https://github.com/electron-userland/electron-packager/issues/806#issuecomment-367744862 would be the way to go if you still wanted to write your own module. Writing a separate module would have the advantage of having users who do not necessarily want to use electron-builder (or Electron Forge) and want to handle their build system themselves.
