### ISSUE TITLE
Add support for a configuration file

### ISSUE THREAD

**Issue by thomas3577** [electron-userland/electron-packager#809]
I think it would be great to configure the electron-packager with a config file. Something like:

`electron-packager . electron-packager.json`

**electron-packager.json**
`
{
  "output": "packager",
  "arch": "ia32",
  "plattform": "win32",
  "icon": "favicon.ico"
  ...
}
`

**Comment by malept** [comment]
I'm not inclined to do this within Electron Packager proper, because there are unresolved questions about whether the config file takes precedence over the command line arguments (I don't think there's a clear answer there), and I don't think the maintenance cost / feature benefit ratio is worth it. I encourage anyone who needs this feature to either:

* use [Electron Forge](https://github.com/electron-userland/electron-forge#readme), which is a complete development workflow for Electron apps (which uses Electron Packager internally) that puts its configuration either in `package.json` or a separate JavaScript file, or
* create a new Node module which wraps Electron Packager to provide this functionality (in the same way that `electron-packager-interactive` and `grunt-electron` have done), in which case I will happily link to it in the readme under related packages.
