### ISSUE TITLE
I hope electron-packager will test the program while packaging

### ISSUE THREAD

**Issue by dotku** [electron-userland/electron-packager#824]
I found there are few modules are missing after packaging, if electron could test the module while packaging would be nice.

**Comment by malept** [comment]
That's probably not going to happen. However if there are modules in `dependencies` which are missing after packaging, that is a bug and it would be much appreciated if there were steps to reproduce this behavior.

**Comment by malept** [comment]
Since the original issue reporter has not responded to the request for additional information in about two weeks, I'm going to assume that they either found the answer in another manner or decided not to pursue the described bug. If I'm incorrect, they can respond with answers to the questions posed, and I'll reopen.
