### ISSUE TITLE
An .electronignore file ?

### ISSUE THREAD

**Issue by fritx** [electron-userland/electron-packager#828]
* [x] I have read the [contribution documentation](https://github.com/electron-userland/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

Writing too much in `--ignore` option is annoying, how about taking an `.electronignore` file?
Just like `.gitignore`, `.npmignore`, `.eslintignore`, etc.

```sh
electron-packager app --ignore \"(yarn\\.lock|package-lock\\.json|__test__|\\.map|src\\/web)$\"
```

Ref: https://github.com/electron-userland/electron-packager/blob/master/docs/faq.md#why-isnt-my-ignore-option-working

Btw, I can't make ignoring `package-lock.json` work.

**Comment by malept** [comment]
There was an attempt at an electronignore file in https://github.com/electron-userland/electron-packager/pull/376 but I was not a fan of it. I said that I would rather see a way to specify all config options in the `package.json`. Now I'm hesitant to do that because it adds a lot of complexity for a small percentage of users. I would instead suggest that people either use Electron Forge (which has that feature, and why I know how much work it is to do that correctly), or that someone write a thin wrapper around Electron Packager's API. If someone does end up doing that, they should take inspiration from how Electron Forge does it, because you'd also have to remove the config from the copied `package.json` for security purposes.

Regarding your problem, instead of a bunch of `|`s, I would either just have multiple `--ignore` params, or run a script that uses the Packager API instead of invoking the Packager CLI.

**Comment by fritx** [comment]
@malept thanks for your time, great answer!
