### ISSUE TITLE
Can't figure out how extraResource works

### ISSUE THREAD

**Issue by hibiyasleep** [electron-userland/electron-packager#829]
* [x] I have read the [contribution documentation](https://github.com/electron-userland/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Please describe your issue:

My project uses [electron-vue template](https://github.com/SimulatedGREG/electron-vue/), and have a directory structure as like below:

```
* /
+ .electron-vue
| + build.config.js // which includes electron-packager options
+ src
| + main ...
| + renderer ...
* package.json
* extlib.so // <- main problem
```

Under this structure, I'm trying to copy `extlib.so` into `resources` of result, but any combination I tried doesn't worked at all. I tried (quite a bruteforce):

* `'extlib.so'`
* `'./extlib.so'`
* `'../extlib.so'`
* `__dirname + '/../extlib.so'`
* `path.resolve(path.join(__dirname, '../extlib.so'))`, this results absolute path of `extlib.so`.

### Console output when you run electron-packager with the environment variable `DEBUG=electron-packager`. Please include the stack trace if one exists.

Nothing special, doesn't refer `extraResource` except saying **Packager Options** at first. 

### What command line arguments are you passing? Alternatively, if you are using the API, what
parameters are you passing to the `packager()` function?

```
module.exports = {
  arch: 'armv7l',
  asar: true,
  dir: path.join(__dirname, '../'),
  ...
  overwrite: true,
  platform: 'linux',
  extraResource: [
    /* things I referenced above */
  ]
}
```

**Comment by malept** [comment]
Paths given to `extraResource` should be relative to whatever directory you're calling the script from that invokes the Electron Packager API, but definitely absolute paths should work. All it does is call `fs.copy()`.

In order to debug your problem further, we need a minimal testcase to reproduce your problem. Using the [`electron-quick-start`](https://github.com/electron/electron-quick-start) repository as a base, could you please create a minimal Electron app that illustrates the issue you described, and post a link to it here?
