### ISSUE TITLE
Electron 2.0版本打包支持

### ISSUE THREAD

**Issue by BruceAn1978** [electron-userland/electron-packager#840]
* [ ] I have read the [contribution documentation](https://github.com/electron-userland/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [ ] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [ ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

**Please describe your issue:**
本地安装Electron 2.0版本后，打包的时候报错，找不到electron相关命令行文件。应该是2.0的文件夹结构等方面改变了。

**Console output when you run electron-packager with the environment variable `DEBUG=electron-packager`. Please include the stack trace if one exists.**

```
Put the console output here
```

**What command line arguments are you passing? Alternatively, if you are using the API, what
parameters are you passing to the `packager()` function?**

```
Put the arguments or parameters here
```

**Please provide either a failing minimal testcase (with a link to the code) or detailed steps to
reproduce your problem. Using [electron-quick-start](https://github.com/electron/electron-quick-start)
is a good starting point.**

**Comment by malept** [comment]
Thanks for filing an issue! In order to help you with your problem, we're going to need more information about it. In particular:

* Console output when you run electron-packager with the environment variable `DEBUG=electron-packager`. Please include the stack trace if one exists.

* What command line arguments are you passing? Alternatively, if you are using the API, what
parameters are you passing to the `packager()` function?

* Please provide either a failing minimal testcase (with code) or detailed steps to reproduce your
problem. Using [electron-quick-start](https://github.com/electron/electron-quick-start) is a good starting point.

Additionally, it would be very helpful if it was translated into English. The maintainers of this module cannot read Chinese, and don't really want to rely on automated translation tools to try to understand your issue, because it may not be accurate.

**Comment by BruceAn1978** [comment]
package.json
`"scripts":
  {
    "start": "electron .",
    "package": "electron-packager ./ FileAssistant --all --out ./target --version 3.0.0 --overwrite --icon=./app/img/forp.ico --DEBUG=electron-packager"
  },`

Command
`npm run-script package`

Console
`PS F:\electron\large-file-assistant> npm run-script package

> large-file-assistant@3.0.0 package F:\electron\large-file-assistant
> electron-packager ./ FileAssistant --all --out ./target --version 3.0.0 --overwrite --icon=./app/img/app.ico --DEBUG=electron-packager

Unable to determine Electron version. Please specify an Electron version

For more information, please see
https://github.com/electron-userland/electron-packager/blob/master/docs/api.md#electronversion


npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! large-file-assistant@3.0.0 package: `electron-packager ./ FileAssistant --all --out ./target --version 3.0.0 --overwrite --icon=./app/img/app.ico --DEBUG=electron-packager`
npm ERR! Exit status 1
npm ERR!npm ERR! Failed at the large-file-assistant@3.0.0 package script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Bruce\AppData\Roaming\npm-cache\_logs\2018-05-13T00_01_40_586Z-debug.log`

**Comment by malept** [comment]
Can you please paste the full `package.json`?

**Comment by BruceAn1978** [comment]
package.json
`{
  "name": "large-file-assistant",
  "version": "3.0.0",
  "description": "Large File Assistant",
  "main": "main.js",
  "scripts":
  {
    "start": "electron .",
    "package": "electron-packager ./ FileAssistant --all --out ./target --version 3.0.0 --overwrite --icon=./app/img/forp.ico --DEBUG=electron-packager"
  },
  "author": "Bruce",
  "license": "ISC",
  "dependencies":
  {
    "nconf": "^0.10.0"
  },
  "devDependencies":
  {
    "electron-packager": "^12.0.2"
  }
}
`

**Comment by malept** [comment]
You need to add `electron` to your `devDependencies`, for example `npm install --save-dev electron`. Otherwise there is no way for Electron Packager to know what Electron version you wish to use.

If you have more questions about usage, I encourage you to read the [frequently asked
questions](https://github.com/electron-userland/electron-packager/blob/master/docs/faq.md),
and visit one of the several [community-driven sites](https://github.com/electron/electron#community), which will have more people available to answer your questions.

**Comment by BruceAn1978** [comment]
Thanks!

Let me have a trying.

**Comment by BruceAn1978** [comment]
I have installed electron 2.0 to project location by `npm install --save-dev electron`.
It still can not work,Here are some errors:
`PS F:\electron\large-file-assistant> npm run-script package

> large-file-assistant@3.0.0 package F:\electron\large-file-assistant
> electron-packager ./ FileAssistant --all --out ./target --version 3.0.0 --overwrite --icon=./app/img/app.ico --DEBUG=electron-packager



... and 1 more
Failed to find Electron v2.0.0 for linux-mips64el at https://github.com/electron/electron/releases/download/v2.0.0/electron-v2.0.0-linux-mips64el.zip
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! large-file-assistant@3.0.0 package: `electron-packager ./ FileAssistant --all --out ./target --version 3.0.0 --overwrite --icon=./app/img/app.ico --DEBUG=electron-packager`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the large-file-assistant@3.0.0 package script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Bruce\AppData\Roaming\npm-cache\_logs\2018-05-13T11_38_10_002Z-debug.log`

**Comment by BruceAn1978** [comment]
It's not the package's problem, but electron v2.0.
I packaged success for only window's platform. It seems no file found for mac or linux platform by electron v2.0
