### ISSUE TITLE
Unable to find valid app after compiling

### ISSUE THREAD

**Issue by quantumproducer** [electron-userland/electron-packager#842]
**Please describe your issue:**

Compiled with electron-packager '12.0.2'

<img width="344" alt="screen shot 2018-05-14 at 00 13 00" src="https://user-images.githubusercontent.com/11827932/39977986-b73d7af8-570b-11e8-934d-d3af7faea083.png">

(osx won't let me copy the text)

Runs fine when not packaged.

**Comment by malept** [comment]
Thanks for filing an issue! In order to help you with your problem, we're going to need more information about it. In particular:

* Console output when you run electron-packager with the environment variable `DEBUG=electron-packager`. Please include the stack trace if one exists.

* What command line arguments are you passing? Alternatively, if you are using the API, what
parameters are you passing to the `packager()` function?

* Please provide either a failing minimal testcase (with code) or detailed steps to reproduce your
problem. Using [electron-quick-start](https://github.com/electron/electron-quick-start) is a good starting point.

**Comment by cornwang** [comment]
i aslo have this problem :(
