### ISSUE TITLE
Packaged app on MacOs not working

### ISSUE THREAD

**Issue by tigierrei** [electron-userland/electron-packager#878]
I packaged my app on MacOs High Sierra 10.13.6 and tried to run it by I get the following error:
<img width="461" alt="senza titolo" src="https://user-images.githubusercontent.com/1363669/43990299-7aaa155c-9d5a-11e8-97bd-b361d05fe858.png">

The command that I used was: `electron-packager Launcher SNLauncher --platform=darwin --arch=x64`

If I try to package the app on windows I get another error with the following details:
https://pastebin.com/VdMt09xv

The packaged version for Windows built on Windows run perfectly

**Comment by malept** [comment]
Regarding the first issue, my guess is that you're running your macOS app by double-clicking your `.app` file, instead of opening it in the terminal. You generally cannot access shell environment variables from your app without some workarounds (this is not an Electron-specific problem).

In order to debug your second problem further, we need a minimal testcase to reproduce it. Using the [`electron-quick-start`](https://github.com/electron/electron-quick-start) repository as a base, could you please create a minimal Electron app that illustrates the issue you described, and post a link to it here?

Please also indicate the version of Windows and the permission level of the user (normal, admin, etc.).

**Comment by tigierrei** [comment]
Thank you for the quick reply. I will try everything you listed and I will inform you

**Comment by tigierrei** [comment]
For the first error I tried executing the app using `open <path to the app file>` but it gave me the same error. On windows 10 it works.
For the second error, the folder is set up like this:
`electron/Electron.app/Contents/Resources/app/
  ├── package.json
  └── index.js`

**Comment by malept** [comment]
In order to debug your problem further, we need a minimal testcase to reproduce your problem. Using the [`electron-quick-start`](https://github.com/electron/electron-quick-start) repository as a base, could you please create a minimal Electron app that illustrates the issue you described, and post a link to it here?
