### ISSUE TITLE
cannot find module index.js

### ISSUE THREAD

**Issue by skypatel** [electron-userland/electron-packager#879]
cannot find module ~\resource\app.asar\index.js

![err](https://user-images.githubusercontent.com/38347060/44206514-b71b4d00-a177-11e8-8fea-48af2778f5b5.png)

i think problem is in asar.

i am using electron-packager . HappyStudio --platform=win32 --arch=x64 --asar=true

**Comment by malept** [comment]
In order to debug your problem further, we need a minimal testcase to reproduce your problem. Using the [`electron-quick-start`](https://github.com/electron/electron-quick-start) repository as a base, could you please create a minimal Electron app that illustrates the issue you described, and post a link to it here?
