### ISSUE TITLE
Cannot find module 'rxjs'

### ISSUE THREAD

**Issue by shavenwalrus** [electron-userland/electron-packager#882]
* [x] I have read the [contribution documentation](https://github.com/electron-userland/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

Since latest update when building for windows (npm run start electron:windows) the executable fails with the following error:

![image](https://user-images.githubusercontent.com/8065548/44321802-74b28280-a48d-11e8-8213-4c63e92c9eff.png)

**Comment by malept** [comment]
In order to debug your problem further, we need a minimal testcase to reproduce your problem. Using the [`electron-quick-start`](https://github.com/electron/electron-quick-start) repository as a base, could you please create a minimal Electron app that illustrates the issue you described, and post a link to it here?

**Comment by shavenwalrus** [comment]
It was a silly error on my part, please disregard and sorry for the inconvenience.
