### ISSUE TITLE
Doesn't build Electron beta 4.x.x or nightly 4.x.x executables for Linux

### ISSUE THREAD

**Issue by coreybruce** [electron-userland/electron-packager#901]
Compiled executable files for Linux are not compiled properly, not clickable executable s and show up as a shared file with other bugs from it not being properly compiled also noticed other stuff on the Windows compiled binary missing the icon I set for it ect.

**Comment by malept** [comment]
Thanks for filing an issue! Unfortunately, I cannot reproduce your problem with the information provided. My steps (on a Linux host, for a Linux target):

```
git clone https://github.com/electron/electron-quick-start && cd electron-quick-start
# edit package.json to use exactly electron-4.0.0-beta.5
npm install
npm install --save-dev electron-packager
$(npm bin)/electron-packager .
./electron-quick-start-linux-x64/electron-quick-start
```

In order to help you with your problem, we're going to need more information about it. In particular:

* Console output when you run electron-packager with the environment variable `DEBUG=electron-packager` _(instructions for [Windows](https://github.com/visionmedia/debug#windows-command-prompt-notes) and [non-Windows](https://en.wikipedia.org/wiki/Environment_variable#Unix))_. Please include the stack trace if one exists.

* What command line arguments are you passing? Alternatively, if you are using the API, what
parameters are you passing to the `packager()` function?

* **Please provide either a failing minimal testcase (with code) or detailed steps to reproduce your
problem.** Using [electron-quick-start](https://github.com/electron/electron-quick-start) is a good starting point.

**Comment by malept** [comment]
It's runnable from the command line (which is why I was unable to reproduce in the first place), but I can reproduce the behavior of trying to run it from Nautilus and getting the error message `There is no application installed for "shared library" files."

Unfortunately, this is a bug in Electron itself, not Electron Packager. Upstream changed their build process for 4.0 and this may have been one of the unintended side effects. Can you please file a bug in the Electron issue tracker so those developers are made aware?

For a workaround, you can try using `electron-installer-debian` to create an installable .deb file (with .desktop launcher shortcut) or `electron-installer-snap` to create a snap file.

**Comment by coreybruce** [comment]
@malept It is runable yes bug yes. but it isn't correctly compiling. I will make a bug report on Electron to get this fixed.

**Comment by mbigger** [comment]
same problem，how to solve it?

**Comment by coreybruce** [comment]
Best solution unless you don't package it like I did for my software for Arch/Manjaro is to just make a desktop shortcut to it

**Comment by mbigger** [comment]
> 最好的解决方案，除非你没有像我为Arch / Manjaro的软件那样打包，只是为它创建一个桌面快捷方式

but even if i make a desktop shortcut for it, i cannot start it, when i double click the icom, no response.

this is the content of my desktop file:
```
[Desktop Entry]
Name=My Application
Exec=/root/electron-quick-start/node_modules/electron/dist/electron
Terminal=false
Type=Application
StartupNotify=true
Encoding=UTF-8
```

**Comment by codebytere** [comment]
@mbigger did you mean to ping me? i'm not sure what help i can be here, unfortunately

**Comment by mbigger** [comment]
@codebytere sorry ，i want to @coreybruce

**Comment by coreybruce** [comment]
That's because on your example desktop shortcut your not even linking it to your application you made also you need to right click the application and go into properties than tick "allow this file to run" or something similar so it can run.

**Comment by mbigger** [comment]
@coreybruce Of course , I did this , chmod +x , and allow it to run. The icon has changed to the same as an
 executable program.

**Comment by krastanov-veselin** [comment]
Is this thread even serious, last comment is Jul 16 2019 and this is like a dealbreaker bug and it is closed for what reason?

**Comment by malept** [comment]
>  it is closed for what reason?

From https://github.com/electron/electron-packager/issues/901#issuecomment-433101967:

> Unfortunately, this is a bug in Electron itself, not Electron Packager. Upstream changed their build process for 4.0 and this may have been one of the unintended side effects.

The related Electron issue: https://github.com/electron/electron/issues/15406
