### ISSUE TITLE
Packaging python scripts stored as exe files with app.

### ISSUE THREAD

**Issue by HeroicosHM** [electron-userland/electron-packager#902]
* [x] I have read the [contribution documentation](https://github.com/electron-userland/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

**Explanation:**
I am trying to develop an app with electron that runs information from the html documents, through a JavaScript linker script, to end up running in a Python script that uploads information to a database. This app is intended for eventual distribution, so the python scripts are packaged in a .exe file (I am using Windows). When running the application as is, it works perfectly. However, after packaging the app using electron packager, it does not. For some reason, even though nothing appears to not be working visually, the information does not end up in the database. From what I can tell, this is because the python .exe file never gets run, even though the JavaScript in charge of running it will not throw any errors. However, when I cd into the electron/resources/app directory and run "electron ." or "npm start", the script runs normally and properly puts information into the database.

**Help Request:**
Is there a way for me to also make sure that the python.exe file also ends up getting run properly when the app has been packaged?

**Comment by malept** [comment]
Without any context as to how you're using Electron Packager, there could be one of two problems:

* You're using the `asar` functionality with the executables. My understanding is that Windows cannot execute machine code that is in asar files.
* You're referencing files with [relative paths instead of absolute paths](https://github.com/electron-userland/electron-packager/blob/v12.2.0/docs/faq.md#why-isnt-the-relative-path-in-my-app-code-working).

For further assistance, please consult the [community forums](https://electronjs.org/community). This issue tracker is meant for bugs and feature requests.

**Comment by HeroicosHM** [comment]
Thank you for your quick response.

**Comment by HeroicosHM** [comment]
For the record, the references with relative paths was the problem, and it works in the `asar` format as well.
