### ISSUE TITLE
 Can not play window installation package under mac system

### ISSUE THREAD

**Issue by drdevelop** [electron-userland/electron-packager#906]
Mac system packaged into a window installation package set platform=win32 command line will appear "... and 1 more", then no response, and then package failure

**Comment by malept** [comment]
Thanks for filing an issue! In order to help you with your problem, we're going to need more information about it. In particular:

* Console output when you run electron-packager with the environment variable `DEBUG=electron-packager` _(instructions for [Windows](https://github.com/visionmedia/debug#windows-command-prompt-notes) and [non-Windows](https://en.wikipedia.org/wiki/Environment_variable#Unix))_. Please include the stack trace if one exists.

* What command line arguments are you passing? Alternatively, if you are using the API, what
parameters are you passing to the `packager()` function?

* Please provide either a failing minimal testcase (with code) or detailed steps to reproduce your
problem. Using [electron-quick-start](https://github.com/electron/electron-quick-start) is a good starting point.

----

About "... and 1 more": https://github.com/electron-userland/electron-packager/issues/218#issuecomment-240582651

**Comment by drdevelop** [comment]
@malept this is my code: "electron-packager . checking --platform=win32 --out ../testApp-win --arch=x64 --electron-version=2.0.9 --icon=icons/dev.ico --overwrite", 
I am executing this statement in the build command of the script field of package.json
But my npm run build is finished, the command line shows... and 1 more there is no reaction.

**Comment by malept** [comment]
In order to help you with your problem, we're going to need more information about it. In particular:

* Console output when you run electron-packager **with the environment variable `DEBUG=electron-packager` _(instructions for [Windows](https://github.com/visionmedia/debug#windows-command-prompt-notes))_**.

**Comment by drdevelop** [comment]
@malept this is Console all output 
> electron-packager . checking --platform=win32 --out ../testApp-win --arch=x64 --electron-version=2.0.9 --icon=icons/dev.ico --overwrite


... and 1 more

**Comment by malept** [comment]
1. Maximize your command prompt window
2. Run `SET DEBUG=electron-packager`
3. Run `electron-packager . checking --platform=win32 --out ../testApp-win --arch=x64 --electron-version=2.0.9 --icon=icons/dev.ico --overwrite`

Copy/paste the output here.

**Comment by drdevelop** [comment]
@malept Is this the way to write "build": "DEBUG=electron-packager&&electron-packager . checking --platform=win32 --out ./dist --arch=x64 --electron-version=2.0.9 --icon=icons /dev.ico --overwrite", but if you write this, the packaging app for platform win32 x64 using electron v2.0.9 appears, and then nothing happens. Because i am use it in package.json

**Comment by drdevelop** [comment]
finally, show error "rcedit.exe failed with exit code 1. Reserved header is not 0 or image type is not icon for 'i'
Fatal error: Unable to set icon"

**Comment by drdevelop** [comment]
@malept I found the problem with the icon icon, but my icon icon format is ico, the size is also 256*256, what is the reason? If the icon icon is not set, it can be packaged into an exe package.

**Comment by malept** [comment]
It seems that rcedit (the dependency Electron Packager uses to customize the Windows executable) does not think that you're passing in a proper ICO file.
