### ISSUE TITLE
i cant run my electron app after installing Git for windows

### ISSUE THREAD

**Issue by ESHANNIMESHA** [electron-userland/electron-packager#907]
**i have install git for windows and after that i cant run any electron app using npm run, after removing GIT it doesn't worked, it showing this on visual studios terminal**

```
PS E:\projects\electron test\gymapp> npm run
Lifecycle scripts included in sample_gym_app:
  start
    electron .

available via `npm run-script`:
  pack
    build --dir
```

**How Do i fix this and run my app ?**

**Comment by malept** [comment]
This doesn't sound like a bug with Electron Packager. If you're using Node 11 and Electron 4 beta, there was an [issue there](https://github.com/electron/electron/issues/15467) that has since been fixed. Otherwise, this sounds like an NPM problem. You can find more assistance with NPM at their [community support forum](https://npm.community/c/support).
