### ISSUE TITLE
Windows exe not able to resolve dependency set via git URL

### ISSUE THREAD

**Issue by anirbanctts** [electron-userland/electron-packager#913]
I have an electron app that refers a component from git that provides some angular Js features.
the dependency is set like  ...  "componentname" :  "git+ssh://git@gitlaburl/componentname.git"

while packaging and creating exe it looks like the dependency is not getting resolved whereas in debug mode (npm start) it works perfectly.

the same also working perfectly in Mac.

Please let me know how can we resolve this still keeping dependency from GIT

**Comment by malept** [comment]
In order to debug your problem further, we need a minimal testcase to reproduce your problem. Using the [`electron-quick-start`](https://github.com/electron/electron-quick-start) repository as a base, could you please create a minimal Electron app that illustrates the issue you described, and post a link to it here? You can use a public GitHub repo (but using the SSH git repo URL) for the dependency.

If this is reproducible, I suspect it may be related to the pruning feature.
