### ISSUE TITLE
Error: Chromium revision is not downloaded

### ISSUE THREAD

**Issue by raviregina** [electron-userland/electron-packager#920]
Hi,
    i'm using electron packager module to create the executable file for my node application. After converting the node application to example.exe, i launched the example.exe file. It will threw the exception like  **Chromium revision is not downloaded** when i launch the chromium browser using my example.exe file.

how can i rectify this problem?

**Comment by raviregina** [comment]
yes, i'm using puppeteer.

- I want instructions for windows and linux

- But in OS X, the executable file working correctly

**Comment by raviregina** [comment]
![screenshot 5](https://user-images.githubusercontent.com/41115011/50016324-dc697c00-ffee-11e8-8a8a-8dca29460443.png)

- i got this error

**Comment by malept** [comment]
Is this an existing web app, or is this actually just a Node app you want packaged? If it's the second option, you probably want to use [`pkg`](https://github.com/zeit/pkg) instead. This is because with Electron, not only will you be packaging Electron's version of Chromium, but also Puppeteer has its own version that it's trying (and failing) to download. Unfortunately, you'll find the [same error](https://github.com/zeit/pkg/issues/204) there.
