### ISSUE TITLE
no such file or directory LICENSES.chromium.html

### ISSUE THREAD

**Issue by roccomuso** [electron-userland/electron-packager#921]
Tried to run:

> electron-packager . --out=dist --asar --overwrite --all --icon './ui/icons/icon128.png'

And got this error:

```
ENOENT: no such file or directory, stat 'dist/TestApp-win32-ia32/LICENSES.chromium.html'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! test-app@0.0.1 build: `electron-packager . --out=dist --asar --overwrite --all --icon './ui/icons/icon128.png'`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the test-app@0.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**electron**: `3.0.11`
**electron-packager**: `13.0.0`

**Comment by malept** [comment]
Thanks for filing an issue! In order to help you with your problem, we're going to need more information about it. In particular:

* Console output when you run electron-packager with the environment variable `DEBUG=electron-packager` _(instructions for [Windows](https://github.com/visionmedia/debug#windows-command-prompt-notes) and [non-Windows](https://en.wikipedia.org/wiki/Environment_variable#Unix))_. Please include the stack trace if one exists.

* Please provide either a failing minimal testcase (with code) or detailed steps to reproduce your
problem. Using [electron-quick-start](https://github.com/electron/electron-quick-start) is a good starting point.
