### ISSUE TITLE
some file fail to package in the mac app

### ISSUE THREAD

**Issue by skykingit** [electron-userland/electron-packager#925]
When i package the app in the mac, after the package was finished without no error
i open the app, the page lost some css and js files.
i check the app's content ,i found some files is 0 bytes

**Comment by skykingit** [comment]
hi ,here is the my command line:
electron-packager ./ name --platform=darwin --out ./app --app-version 1.0.1 --overwrite --icon=public/img/logo.hqx 

and the console log is :
$ electron-packager ./ pwallet --platform=darwin --out ./app --app-version 1.0.1 --overwrite --icon=public/img/logo.hqx  DEBUG=electron-packager
Packaging app for platform darwin x64 using electron v3.0.0
Wrote new app to app/pwallet-darwin-x64
✨  Done in 15.43s.

no error is here ,but when i open the app ,some css and javascript file is missing

i open the app's package contents ,i found the missing files is empty file

**Comment by malept** [comment]
In order to debug your problem further, we need a minimal testcase to reproduce your problem. Using the [`electron-quick-start`](https://github.com/electron/electron-quick-start) repository as a base, could you please create a minimal Electron app that illustrates the issue you described, and post a link to it here?

**Comment by skykingit** [comment]
sorry to bother you guys. 
i fixed the problem, the reason is the MAC's file permission Issue.
i set 777 for the project files, everything is ok.
beacuse no error log show before , i miss the basic question, thanks again
