### ISSUE TITLE
Not creating executable file

### ISSUE THREAD

**Issue by phucnguyenbn9x** [electron-userland/electron-packager#938]
I'm using electron v4.0.2 and when i run "electron-packager .", it not create executable file in the output directory.

**Comment by malept** [comment]
Thanks for filing an issue! In order to help you with your problem, we're going to need more information about it. In particular:

* Console output when you run electron-packager with the environment variable `DEBUG=electron-packager` _(instructions for [Windows](https://github.com/visionmedia/debug#windows-command-prompt-notes) and [non-Windows](https://en.wikipedia.org/wiki/Environment_variable#Unix))_. Please include the stack trace if one exists.

* Please provide either a failing minimal testcase (with code) or detailed steps to reproduce your
problem. Using [electron-quick-start](https://github.com/electron/electron-quick-start) is a good starting point.

**Comment by bhangalekunal** [comment]
My electron runnable file is works by command ./filename but don't work by double clicking

**Comment by malept** [comment]
@bhangalekunal is this on Linux? If so, this is a known issue that is not specific to Electron Packager: https://github.com/electron/electron/issues/15406
