### ISSUE TITLE
App cant read config.js

### ISSUE THREAD

**Issue by Mrmatiiii** [electron-userland/electron-packager#945]
Hello, i have problem with my app
after package with electron packager i run app and this app dont read a config.js i need config.js to be available to user for changes but app do not read it and idk why do anyone have idea for this inssue

**Comment by malept** [comment]
Unfortunately, due to the limited amount of time of the maintainers and the limited amount of information present in this issue, we cannot help debug your app at this time. Instead, you should make sure your issue is not already answered in our [Frequently Asked Questions](https://github.com/electron-userland/electron-packager/blob/master/docs/faq.md) document, and consider using one of the [community forums](https://electronjs.org/community), as there are more people there available to answer questions.
