### ISSUE TITLE
Error: Path must be a string. Received undefined 2

### ISSUE THREAD

**Issue by MYDIH** [electron-userland/electron-packager#946]
Hi,

This issue (#536) is still present. I guess it's because commander is trying to parse the first argument to a path, but I think not giving a path as first argument of the program is wrong. A packaged program should be run exactly the same way as an un-packaged one.

What do you think ? 

EDIT: commander [issue](https://github.com/tj/commander.js/issues/912)

**Comment by malept** [comment]
This is not a bug in Electron Packager itself. The behavior you describe is how Electron works internally.

To recap, when your Electron app's `main` script consists of only:

```javascript
console.log(process.argv)
```

In development mode (`npm start` in the `electron-quick-start` repo), it prints out:

```javascript
[ '/tmp/electron-quick-start/node_modules/electron/dist/electron', '.' ]
```

When it's packaged, it prints out:

```javascript
[ '/tmp/electron-quick-start/electron-quick-start-linux-x64/electron-quick-start' ]
```

This is because `npm start` runs `electron .`. What you should do is use [`app.isPackaged`](https://electronjs.org/docs/api/app#appispackaged) to determine whether you need to change `process.argv` before passing it to `commander`.
