### ISSUE TITLE
Binding.node is not a valid Win32 application

### ISSUE THREAD

**Issue by moialbla** [electron-userland/electron-packager#948]
Hi everyone,

I was trying to create an electron build for x32 and x64 and when I launch the x64 application electron throws the following message:
![image](https://user-images.githubusercontent.com/14232214/52997381-b57d5b00-3420-11e9-9928-a291cbe37d88.png)

However, the x32 application works fine.
What am I doing wrong? Any opinions or suggestions?

Here my machine and project features:
- W10 64bits
- Node 10..13.0
- NPM 6.4.1
- electron 4.0.1
- electron-builder 20.38.2
- electron-packager 12.1.0
- electron-rebuild 1.8.2
- electron-reload 1.2.5
- node-gyp 4.0.0

Thank you in advance.

**Comment by malept** [comment]
Thanks for filing an issue! In order to help you with your problem, we're going to need more information about it. In particular:

* Console output when you run electron-packager with the environment variable `DEBUG=electron-packager` _(instructions for [Windows](https://github.com/visionmedia/debug#windows-command-prompt-notes) and [non-Windows](https://en.wikipedia.org/wiki/Environment_variable#Unix))_. Please include the stack trace if one exists.

* What command line arguments are you passing? Alternatively, if you are using the API, what
parameters are you passing to the `packager()` function?

* Please provide either a failing minimal testcase (with code) or detailed steps to reproduce your
problem. Using [electron-quick-start](https://github.com/electron/electron-quick-start) is a good starting point.

**Comment by malept** [comment]
Without having **any** context, I would suggest upgrading to Electron 4.0.4 or greater, and electron-rebuild 1.8.3 or greater. It probably has nothing to do with Electron Packager.
