### ISSUE TITLE
Unable to access local library

### ISSUE THREAD

**Issue by pilz97** [electron-userland/electron-packager#988]
Hi,

I have an angular application with multiple projects, that's why i created an angular library inside my application where i manage shared components, services...

For using the library in the projects i built the library and installed it, so in the package.json --> dependencies there is a entry like: "my-lib": "file:dist/my-lib",

In my AppModule i importet my library under the imports:
import { MyLibModule } from 'my-lib';
import { TestComponent } from './components/test/test.component';

`@NgModule({
  declarations: [TestComponent],
  imports: [
    CommonModule,
    MyLibModule,
  ],
  exports: [
    MyLibModule,
  ],
})`

In my library i have a component named 'settings' when i use the component it will not be displayed in the electron window.. but with ng serve it works fine!
I also tried to display the developer tools but there is now error in the console

Can anyone help me?

**Comment by malept** [comment]
Unfortunately, due to the limited amount of time of the maintainers and the limited amount of information present in this issue, we cannot help debug your app at this time. Instead, you should make sure your issue is not already answered in our [Frequently Asked Questions](https://github.com/electron-userland/electron-packager/blob/master/docs/faq.md) document, and consider using one of the [community forums](https://electronjs.org/community), as there are more people there available to answer questions.

That being said, I suspect that some sort of webpack config or plugin will resolve this issue.
